In [1]:
pip install profanity_check

Collecting profanity_check
  Using cached profanity_check-1.0.3-py3-none-any.whl (2.4 MB)
Requirement already satisfied: scikit-learn>=0.20.2 in /home/bishal/anaconda3/lib/python3.7/site-packages (from profanity_check) (0.22.1)
Requirement already satisfied: joblib>=0.11 in /home/bishal/anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.20.2->profanity_check) (0.14.1)
Requirement already satisfied: numpy>=1.11.0 in /home/bishal/anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.20.2->profanity_check) (1.18.1)
Requirement already satisfied: scipy>=0.17.0 in /home/bishal/anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.20.2->profanity_check) (1.4.1)
Installing collected packages: profanity-check
Successfully installed profanity-check-1.0.3
Note: you may need to restart the kernel to use updated packages.

In [5]:
from profanity_check import predict, predict_prob

import warnings
warnings.filterwarnings("ignore")


first_cleaner = ['{', '[', '(','$', '#', '<', '-', '+', '±', '∠', '|', 'π','~', '∆' ,'∑', '∏', 'e', 'μ', 'σ', 'n', 'ε', '∞', '' ]
last_cleaner = ['=','}', ']', ')', '°', '|', 'π', '!', '∆', 'γ', 'μ', 'ε', '∞', ]
greek_alphabets = ['Α', 'α', 'Β', 'β', 'Γ', 'γ', 'Δ', 'δ', 'Ε', 'ε', 'Ζ', 'ζ', 'Η', 'η', 'Θ', 'θ', 'Ι', 'ι', 'Κ', 'κ', 'Λ', 'λ', 'Μ', 'μ', 'Ν', 'ν','Ξ', 'ξ', 'Ο', 'ο', 'Π', 'π', 'Ρ', 'ρ', 'Σ', 'σ', 'ς', 'Τ', 'τ', 'Υ', 'υ', 'Φ', 'φ', 'Χ', 'χ', 'Ψ', 'ψ','Ω','ω', '∆' ,'∑', '∏', 'e', 'μ', 'σ', 'n', 'ε', '∞']
wh_list = ['what', 'who', 'whom', 'whose','how', 'where', 'when','why','which']

def clean_garbage(question):
    while ((not question[0].isalnum()) and (question[0] not in first_cleaner) and (question[0] not in greek_alphabets)) or ((not question[-1].isalnum()) and (question[-1] not in last_cleaner) and (question[-1] not in greek_alphabets)):
        if (not question[0].isalnum()) and (question[0] not in first_cleaner) and (question[0] not in greek_alphabets):
            question = question.replace(question[0],'', 1)
        if (not question[-1].isalnum()) and (question[-1] not in last_cleaner) and (question[-1] not in greek_alphabets):
            question = question[::-1].replace(question[::-1][0], '', 1)[::-1]
    return question

def add_punctuation_dots(question):
    unnecessary_in_wh = ['=', '?']
    question_list = question.lower().split(' ')
    question_filt = [True for q in question_list if q in wh_list]
    question_joined = ' '.join(question_list)
    if any(question_filt):
        while question_joined[-1] in unnecessary_in_wh:
            question_joined = question_joined[::-1].replace(question_joined[::-1][0], '', 1)[::-1]
        question_joined = (question_joined).rstrip() + '?'
    else:
        # this while field should be customized later based on other inputs
        while question_joined[-1] == '=':
            question_joined = question_joined[::-1].replace(question_joined[::-1][0], '', 1)[::-1]
        question_joined = question_joined + '=....'
    
    return question_joined.capitalize()


def predict_profanity(question):
    profanity_status, profanity_probability = predict([question]), predict_prob([question])       
#     print(profanity_status, profanity_probability, (int(profanity_status)))
    if int(profanity_status):
        return ({'profanity': bool(profanity_status), 'profanity_probability': round((profanity_probability[0]),4), 'question': question})

    cleaned_garbage_data = clean_garbage(question)
#     print(cleaned_garbage_data)
    final_data = add_punctuation_dots(cleaned_garbage_data)
    return ({'profanity': bool(profanity_status), 'profanity_probability': round((profanity_probability[0]),4), 'cleaned_question': final_data})

In [30]:
# reading a csv file and outputing the cleaned result in csv

import pandas as pd

file_name = 'class11datacollection.csv'
df = pd.read_csv(file_name)
df.head()
# df['Question']
df['Question'] = df['Question'].map(clean_garbage)
df['Question'] = df['Question'].map(add_punctuation_dots)
# df['Question']
df.to_csv(f'cleaned_{file_name}')

In [38]:
# reading a xlsx file and outputting the cleaned result

import pandas as pd

file_name = 'Class11DataCollection.xlsx'
df = pd.read_excel(file_name)
df

,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,1,Device that converts electrical energy into me...,Ac generator,Dc generator,Cell,Dc motor,D
1,2,Alternative current generator is basically bas...,Amperes law,Lenz's law,Faradays law,Coulombs law,C
2,3,"In alternative current generator, ac current r...",20 times per second,50 times per second,Once per second,Twice per second,B
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,Dc motor,Ac generator,Both a and b,B
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Instantaneous velocity,Instantaneous displacement,Instantaneous speed,A
...,...,...,...,...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive,Negative,Zero,Maximum,D
263,264,When an object is moved in gravitational field...,Work done by a constant force,Work done by a variable force,Work done by a gravitational field,Both a and b,C
264,265,System international unit of work done is newt...,Joule,Kelvin,Ampere,Candela,A
265,266,"If angle of work done is less than 90°, then w...",Negative,Positive,Zero,Both a and b,A
266,267,Product of force and displacement is known as,Distance,Speed,Work done,Force,C

In [41]:
# reading a xlsx file and outputting the cleaned result

import pandas as pd

file_name = 'Class11DataCollection.xlsx'
df = pd.read_excel(file_name, sheet_name=None)
df.keys()

dict_keys(['Physics', 'Chemistry', 'Biology', 'Account', 'Business Studies', 'Finance', 'Sociology', 'Math', 'Economics', 'English'])

In [42]:
# reading a xlsx file and outputting the cleaned result

import pandas as pd

file_name = 'Class11DataCollection.xlsx'
df = pd.read_excel(file_name, sheet_name='Biology')
df

,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,1,They are the remains or impressions of living ...,Tissues,Fossils,Calcium,Statutes,B
1,2,It is the study of fossils and their relations...,Embryology,Taxonomy,Physiology,None of these,D
2,3,Man has been able to produce food in greater q...,Mathematics,Space science,Physics,Biology,D
3,4,Taxonomy is the study of:,Functions of different parts of organisms,Naming and classification of organisms,Hereditary characters,Structure and functions of cells,B
4,5,Anatomy deals with the study of:,Relationship between organisms and their envir...,Development of an organism from a fertilized e...,Structure and function of molecular components...,Internal organs of organisms,D
...,...,...,...,...,...,...,...
194,195,At the end of the electron transport chain dur...,Nad,Fad,Oxygen,Hydrogen,C
195,196,During growth fibers elongate greatly:,At right angle to the long axis,Parallel to the long axis,Obliquely to the long axis,In all directions,B
196,197,Which of these is the naturally occurring auxins?,Indole acetic acid,"2, 4-d",Abscisic acid,Butyric acid,A
197,198,The application of auxin in small amount:,Stimulate the growth of leaves,Retard the growth of leaves,Suppress the growth of leaves,Does not affect the growth of laves,D
198,199,Which of these increases the growth rate of is...,Auxins,Cytokinins,Gibberellins,None of these,B

In [43]:
# reading a xlsx file and outputting the cleaned result

import pandas as pd

file_name = 'Class11DataCollection.xlsx'
df = pd.read_excel(file_name, sheet_name=None)
df['Biology']

,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,1,They are the remains or impressions of living ...,Tissues,Fossils,Calcium,Statutes,B
1,2,It is the study of fossils and their relations...,Embryology,Taxonomy,Physiology,None of these,D
2,3,Man has been able to produce food in greater q...,Mathematics,Space science,Physics,Biology,D
3,4,Taxonomy is the study of:,Functions of different parts of organisms,Naming and classification of organisms,Hereditary characters,Structure and functions of cells,B
4,5,Anatomy deals with the study of:,Relationship between organisms and their envir...,Development of an organism from a fertilized e...,Structure and function of molecular components...,Internal organs of organisms,D
...,...,...,...,...,...,...,...
194,195,At the end of the electron transport chain dur...,Nad,Fad,Oxygen,Hydrogen,C
195,196,During growth fibers elongate greatly:,At right angle to the long axis,Parallel to the long axis,Obliquely to the long axis,In all directions,B
196,197,Which of these is the naturally occurring auxins?,Indole acetic acid,"2, 4-d",Abscisic acid,Butyric acid,A
197,198,The application of auxin in small amount:,Stimulate the growth of leaves,Retard the growth of leaves,Suppress the growth of leaves,Does not affect the growth of laves,D
198,199,Which of these increases the growth rate of is...,Auxins,Cytokinins,Gibberellins,None of these,B

In [48]:
a = 'hello there how are you'
# dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']