In [58]:
import pandas as pd

df = pd.read_csv('datas/class11datacollection.csv')

df.columns

Index(['Unnamed: 0', 'S.N.', 'Question', 'Option A', 'Option B', 'Option C',
       'Option D', 'Correct Option'],
      dtype='object')

In [59]:
df.columns

Index(['Unnamed: 0', 'S.N.', 'Question', 'Option A', 'Option B', 'Option C',
       'Option D', 'Correct Option'],
      dtype='object')

In [63]:
df.drop(columns='Unnamed: 0', inplace=True)

In [64]:
df

,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,1,Device that converts electrical energy into me...,Ac generator,Dc generator,Cell,Dc motor,D
1,2,Alternative current generator is basically bas...,Amperes law,Lenz's law,Faradays law,Coulombs law,C
2,3,"In alternative current generator, ac current r...",20 times per second,50 times per second,Once per second,Twice per second,B
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,Dc motor,Ac generator,Both a and b,B
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Instantaneous velocity,Instantaneous displacement,Instantaneous speed,A
...,...,...,...,...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive,Negative,Zero,Maximum,D
263,264,When an object is moved in gravitational field...,Work done by a constant force,Work done by a variable force,Work done by a gravitational field,Both a and b,C
264,265,System international unit of work done is newt...,Joule,Kelvin,Ampere,Candela,A
265,266,"If angle of work done is less than 90°, then w...",Negative,Positive,Zero,Both a and b,A
266,267,Product of force and displacement is known as,Distance,Speed,Work done,Force,C

In [65]:
df.columns

Index(['S.N.', 'Question', 'Option A', 'Option B', 'Option C', 'Option D',
       'Correct Option'],
      dtype='object')

In [68]:
df.drop(columns=df.columns[3:], inplace=True)

In [42]:
df = df.drop(['Option B', 'Option C', 'Option D', 'Unnamed: 0', 'Correct Option'], axis=1)

In [43]:
df

,S.N.,Question,Option A
0,1,Device that converts electrical energy into me...,Ac generator
1,2,Alternative current generator is basically bas...,Amperes law
2,3,"In alternative current generator, ac current r...",20 times per second
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration
...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive
263,264,When an object is moved in gravitational field...,Work done by a constant force
264,265,System international unit of work done is newt...,Joule
265,266,"If angle of work done is less than 90°, then w...",Negative
266,267,Product of force and displacement is known as,Distance

In [7]:
import numpy as np

df['Correct Option'] = np.nan

In [8]:
df

,S.N.,Question,Option A,Correct Option
0,1,Device that converts electrical energy into me...,Ac generator,NaN
1,2,Alternative current generator is basically bas...,Amperes law,NaN
2,3,"In alternative current generator, ac current r...",20 times per second,NaN
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,NaN
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,NaN
...,...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive,NaN
263,264,When an object is moved in gravitational field...,Work done by a constant force,NaN
264,265,System international unit of work done is newt...,Joule,NaN
265,266,"If angle of work done is less than 90°, then w...",Negative,NaN
266,267,Product of force and displacement is known as,Distance,NaN

In [44]:
correct_answers = list(df['Option A'])

In [10]:
correct_answers

['Ac generator',
 'Amperes law',
 '20 times per second',
 'Dc generator',
 'Instantaneous acceleration',
 '(v₁ + v₂)/t',
 'Displacement',
 'Scalar quantity',
 'Degree per second',
 'Angular displacement',
 'Scalar quantity',
 'Two',
 'Small',
 'Changes continuously',
 'Vi = vf + at',
 'Revolution',
 '57.3°',
 '90°',
 'Scalar quantity',
 'Degree per second',
 'Angular displacement',
 'Angular displacement',
 'Equation of continuity',
 '2.7 g cm⁻³',
 'Equation of continuity',
 'High',
 'F = 3.14g/2r',
 'Surface of rotating space',
 'Large gravity',
 'Global pointing system',
 '7.9 km s⁻¹',
 'Equation of continuity',
 'Mgf',
 '1.2041 kg m⁻³',
 'Equation of continuity',
 '1/2(mv)²',
 '1/2 cv²',
 'Capacitor',
 '10⁻² f',
 'Charge',
 'Performance',
 'Linear force',
 'Smaller diameter',
 'Small',
 'Centripetal velocity',
 '107 hz',
 'Microwaves',
 '110°',
 '2 geo-stationary satellites',
 '1 tv channels',
 'Kinetic energies',
 'Wind',
 'Kinetic energy',
 'Sun',
 'Coal',
 "Newton's law",
 '40 n',
 'F = kq1q2/r²',
 '9x10³',
 'Electrostatic',
 'A.b',
 'Straight line',
 'Displacement',
 'Displacement',
 'Displacement',
 'Inelastic',
 'Conserved',
 'Conserved',
 'Distance',
 'Repulsive',
 'Two point charges',
 'Inkjet printer',
 'Attractive force',
 'Force of lines',
 'Paper',
 'Direction',
 'Parallel',
 'Electric field',
 'Nm²c-1',
 'Min',
 'Micro volt',
 'EEG',
 'Eyeretinography',
 'J C-1',
 'Amplitude of lorenzini',
 'Dc circuit',
 'Emf',
 'Zero',
 '2 bev',
 'Energy',
 '1.8x10⁻¹⁹ j',
 '19 j',
 'Slightly more than collector',
 'Rectifier',
 '10 ma',
 'Emitter',
 'Emitter and collector equally doped',
 '1240i + 1180j',
 '1 m',
 'One minute',
 'Increases',
 'A₁V₁ = A₂V₂',
 'Increasing',
 'Flow rate',
 '900 kg m⁻³',
 '2 types',
 '10⁻¹2',
 'Taking several readings',
 'Random error',
 'Random error',
 'Viscous',
 'Laminar flow',
 'Laminar flow',
 'Laminated design',
 'F = (-m/t)v',
 'Arbitrarily',
 'Electric field',
 'Ohms law',
 'National communication',
 'Asynchronized',
 'Earths mass',
 'Geo-asynchronous satellites',
 'Per month',
 'Induced emf',
 'Emf',
 'Deduce emf',
 'Mutual induction',
 'IS units',
 'Moles',
 'Six',
 '2 kind of units',
 'Moles',
 'Two',
 'Physics',
 'Electrons',
 'Physics',
 'Nuclear physics',
 'Diving',
 'Law of conservation of angular velocity',
 'Mid',
 'Angle',
 'A',
 'Rectangular components',
 'Impulse',
 'Displacement',
 'Inward from shore',
 'Impulse',
 'Crumple zone',
 'Mass of satellite',
 'Bruce mccandless',
 'Accessible',
 'Weight',
 'Selected standards',
 'Velocity',
 '2 characteristics',
 'Physics',
 'Relativity',
 'Physics',
 'Matter',
 'Nuclear physics',
 'Second law',
 '-200 n',
 '30 m s⁻¹',
 '6 rad s⁻¹',
 '6.6x10⁻⁹ rad',
 '120 w',
 '200 n',
 '3.3x10³',
 'Slows down',
 'Resistor',
 '0.12x10⁻² v',
 'Faradays law',
 'Right hand rule',
 '367.5 w',
 '5 m s⁻¹',
 '9 j',
 '2.66 and 3.33',
 '30 m s⁻¹',
 'Emf',
 '0.48v',
 'N c-1',
 'Rod',
 'Ilbxcosɵ',
 'Scalar product',
 '2 types',
 'A.b',
 'A.b',
 '2as = vf² - vi²',
 'T = 2vix(sin/g)',
 '8000 kg s⁻¹',
 '2000 m s⁻¹',
 'Rotational kinetic energy',
 '1/4(mv²)',
 '1/4(mv²)',
 'Stops',
 'Moles',
 'Five',
 'Base unit',
 'Radian',
 'Base unit',
 'Significant',
 'Accurate',
 'Limitation of instruments',
 'Gets increased',
 'Limitation of instruments',
 '15 n',
 'Ml⁻¹t⁻¹',
 '(6i + 5j)/7.81',
 'Weight - drag force',
 'Viscosity',
 'Increasing speed',
 'Voltage',
 'R = 0',
 'Transformer',
 'Self-induction',
 '(output power/input power)x100',
 '1 v',
 '10⁻⁶ m',
 'Logic circuits',
 '10²',
 'Frequent error',
 'M',
 'Random error',
 'Limitation of instruments',
 'Different acceleration',
 'Vf = vi + 2as',
 'Vi = vf + at',
 'Upwards positive',
 'Cos⁻¹(ay + by/ax + bx)',
 'Ax + bx',
 'Ay + by',
 'Subtraction of x-components',
 '√((ax + bx)² + (ay + by)²)',
 'Momentum',
 'Line',
 'Cos',
 'Multiplicative property',
 'Remain same',
 'Scalar',
 'Same',
 'Vector quantities',
 'Remain same',
 'Positive direction',
 'Vector addition',
 'Direction',
 'Direction',
 'Cartesian',
 '√(a² + b² + c²)',
 'Vavg = (d/t)',
 'Displacement',
 'Velocity-speed graph',
 'Velocity-speed graph',
 'Displacement',
 '1/2(vxt)',
 'Viscosity',
 'Viscosity',
 'Viscosity',
 'Massive',
 'Increases',
 'Small force',
 'Gravitational field',
 'Remain constant',
 'Positive',
 'Work done by a constant force',
 'Joule',
 'Negative',
 'Distance']

In [45]:
import random

wrong_options = []
for i in range(df.shape[0]):
    sampling = random.choices(correct_answers, k=4)
    wrong_options.append(sampling)

In [14]:
wrong_options

[['Stops', 'Inkjet printer', 'Rectifier', 'Resistor'],
 ['Parallel', 'National communication', 'Relativity', 'Ax + bx'],
 ['Random error', 'EEG', 'Random error', 'A.b'],
 ['Mass of satellite', '2as = vf² - vi²', 'Parallel', 'Gravitational field'],
 ['Equation of continuity', 'Emf', 'Self-induction', 'Moles'],
 ['Angular displacement', 'Physics', 'Cos', 'Slightly more than collector'],
 ['Kinetic energies',
  'Attractive force',
  'Accurate',
  'Multiplicative property'],
 ['Same', 'Vf = vi + 2as', 'Two', 'Surface of rotating space'],
 ['30 m s⁻¹', '2as = vf² - vi²', '90°', 'Subtraction of x-components'],
 ['Vavg = (d/t)', 'Emf', 'One minute', '200 n'],
 ['Sun', '(output power/input power)x100', 'IS units', 'Changes continuously'],
 ['90°', 'Viscosity', 'Voltage', 'Remain same'],
 ['10⁻⁶ m', '6 rad s⁻¹', 'Matter', 'Repulsive'],
 ['1.8x10⁻¹⁹ j', 'Viscosity', 'Mgf', 'Resistor'],
 ['57.3°', 'T = 2vix(sin/g)', '1.8x10⁻¹⁹ j', '2 characteristics'],
 ['Ay + by', 'Vector quantities', 'Scalar quantity', 'Random error'],
 ['Massive', 'Scalar product', 'Moles', 'Self-induction'],
 ['Physics', 'Limitation of instruments', 'National communication', 'Small'],
 ['Multiplicative property', 'Momentum', 'Viscous', '1/2 cv²'],
 ['Smaller diameter', 'Ax + bx', '0.48v', 'Straight line'],
 ['Scalar', '2as = vf² - vi²', 'Vavg = (d/t)', 'Mgf'],
 ['Linear force', '0.48v', 'Remain same', 'Vector addition'],
 ['Attractive force', 'Scalar product', 'Displacement', 'Asynchronized'],
 ['Six', '367.5 w', 'Impulse', 'Velocity-speed graph'],
 ['1 tv channels', 'Mid', 'Displacement', 'Displacement'],
 ['Emf', 'Angular displacement', 'J C-1', 'Random error'],
 ['Degree per second', 'Moles', 'Ax + bx', '1/2 cv²'],
 ['30 m s⁻¹', 'Velocity-speed graph', 'Kinetic energies', 'Remain same'],
 ['10⁻⁶ m', 'Degree per second', 'Angular displacement', 'Energy'],
 ['900 kg m⁻³', 'Amplitude of lorenzini', 'Angle', 'Crumple zone'],
 ['7.9 km s⁻¹', "Newton's law", 'F = (-m/t)v', '2 types'],
 ['8000 kg s⁻¹', '120 w', 'Voltage', 'Transformer'],
 ['Dc generator', 'Joule', 'Kinetic energy', 'Accessible'],
 ['Mutual induction', 'Frequent error', 'Weight', '1/2(vxt)'],
 ['Kinetic energy', 'Positive direction', 'Ax + bx', 'Vector quantities'],
 ['Small', '1 tv channels', 'Diving', 'Angular displacement'],
 ['Random error', 'Rectangular components', 'A.b', "Newton's law"],
 ['2 kind of units', 'Scalar quantity', 'Two point charges', '2.66 and 3.33'],
 ['Resistor', 'Second law', 'Laminated design', 'Equation of continuity'],
 ['Degree per second',
  'Viscosity',
  'Asynchronized',
  'Work done by a constant force'],
 ['Two point charges',
  '8000 kg s⁻¹',
  'Nuclear physics',
  'Angular displacement'],
 ['Linear force', 'Amperes law', 'Gravitational field', '7.9 km s⁻¹'],
 ['Angular displacement', '10⁻⁶ m', '1/2(mv)²', 'Eyeretinography'],
 ['Subtraction of x-components',
  'Conserved',
  'Equation of continuity',
  'Displacement'],
 ['Amplitude of lorenzini', 'A.b', '1 v', '0.48v'],
 ['Distance', '1/4(mv²)', '10⁻⁶ m', 'Straight line'],
 ['7.9 km s⁻¹', 'Scalar', 'Small force', 'Small'],
 ['Significant', '1240i + 1180j', '40 n', 'Radian'],
 ['Vavg = (d/t)',
  'Eyeretinography',
  'Equation of continuity',
  'Increasing speed'],
 ['Faradays law',
  '(output power/input power)x100',
  'Random error',
  'Degree per second'],
 ['Laminated design', 'Displacement', 'Zero', 'Direction'],
 ['Mass of satellite', '1 m', '40 n', 'Inward from shore'],
 ['-200 n', 'Direction', 'Second law', 'Negative'],
 ['National communication', 'A', 'Viscous', 'Parallel'],
 ['20 times per second', 'Upwards positive', '2000 m s⁻¹', 'Rectifier'],
 ['(v₁ + v₂)/t', '2 types', 'Small', 'Emf'],
 ['Zero', '20 times per second', 'Limitation of instruments', '8000 kg s⁻¹'],
 ['Same', 'Parallel', 'One minute', 'Vector quantities'],
 ['Emf', 'Negative', 'Selected standards', 'N c-1'],
 ['1 m', 'Equation of continuity', 'Linear force', 'Energy'],
 ['Remain constant', 'Micro volt', 'Emf', '2 bev'],
 ['Momentum', '0.12x10⁻² v', '900 kg m⁻³', 'A₁V₁ = A₂V₂'],
 ['30 m s⁻¹', 'Displacement', 'F = 3.14g/2r', 'One minute'],
 ['Direction', 'Radian', '20 times per second', 'Electrons'],
 ['Equation of continuity',
  'Mass of satellite',
  'Ac generator',
  '20 times per second'],
 ['Transformer', 'Weight', 'Momentum', 'Electric field'],
 ['7.9 km s⁻¹', 'Joule', 'Five', 'IS units'],
 ['Laminar flow', 'Angular displacement', 'Dc generator', 'Cartesian'],
 ['8000 kg s⁻¹', 'Vector quantities', 'Direction', 'Matter'],
 ['Physics',
  'Law of conservation of angular velocity',
  '2000 m s⁻¹',
  'Force of lines'],
 ['Impulse', '1240i + 1180j', 'Microwaves', 'Increases'],
 ['367.5 w', 'Degree per second', 'Line', '2as = vf² - vi²'],
 ['Large gravity', '6 rad s⁻¹', 'Significant', 'Surface of rotating space'],
 ['Viscous', 'R = 0', '9 j', '1240i + 1180j'],
 ['Subtraction of x-components',
  'Positive',
  'One minute',
  'Equation of continuity'],
 ['Two', 'A₁V₁ = A₂V₂', 'Instantaneous acceleration', '1240i + 1180j'],
 ['Multiplicative property', 'Straight line', '2 types', 'Scalar quantity'],
 ['(v₁ + v₂)/t', 'Surface of rotating space', 'Random error', 'Asynchronized'],
 ['Bruce mccandless', 'Resistor', 'Induced emf', 'Small'],
 ['Physics', 'Base unit', 'Slows down', '6 rad s⁻¹'],
 ['Repulsive', 'Matter', 'Slightly more than collector', 'T = 2vix(sin/g)'],
 ['6.6x10⁻⁹ rad', 'Angle', 'Electric field', 'Angular displacement'],
 ['Distance', '(6i + 5j)/7.81', 'Distance', 'Sun'],
 ['Impulse', 'A.b', 'Revolution', 'Equation of continuity'],
 ['Vi = vf + at', 'Negative', 'Min', 'Moles'],
 ['Viscosity', 'Impulse', 'High', 'Physics'],
 ['Mass of satellite', 'Moles', 'Emf', '2 types'],
 ['Angular displacement',
  'Global pointing system',
  'Impulse',
  'Vector quantities'],
 ['19 j', '1.2041 kg m⁻³', 'Conserved', 'Mutual induction'],
 ['-200 n', '20 times per second', 'Mutual induction', 'Electrostatic'],
 ['2 characteristics', 'Positive', 'Displacement', 'Electric field'],
 ['Small', 'Cartesian', '6.6x10⁻⁹ rad', 'Wind'],
 ['0.12x10⁻² v', 'Different acceleration', '-200 n', 'Two'],
 ['107 hz', 'Random error', 'Nm²c-1', '0.48v'],
 ['Small force', 'F = 3.14g/2r', 'Amperes law', '107 hz'],
 ['Physics', 'Viscous', 'Displacement', '1/2(mv)²'],
 ['Performance', 'Increasing', 'Paper', '10²'],
 ['Increases', '0.12x10⁻² v', 'Accessible', 'R = 0'],
 ['Right hand rule', 'Electrons', 'Vector addition', 'Mass of satellite'],
 ['Weight - drag force', 'Dc circuit', 'Scalar', '200 n'],
 ['Impulse', 'Ohms law', '10⁻² f', 'M'],
 ['Impulse', 'Subtraction of x-components', 'Physics', 'Physics'],
 ['2000 m s⁻¹', 'Viscous', 'Asynchronized', 'Matter'],
 ['Moles',
  'Amperes law',
  'Law of conservation of angular velocity',
  'Angular displacement'],
 ['Geo-asynchronous satellites', 'Increasing speed', 'Ilbxcosɵ', '110°'],
 ['Mass of satellite', 'Ac generator', 'Two', 'Accessible'],
 ['30 m s⁻¹', 'Angle', '2.7 g cm⁻³', 'Slightly more than collector'],
 ['Weight', '30 m s⁻¹', '120 w', 'Electric field'],
 ['Small', 'Attractive force', 'Two', '1/2(mv)²'],
 ['Displacement', 'Capacitor', 'Moles', 'M'],
 ['A.b', '1 v', 'Microwaves', 'Coal'],
 ['Degree per second', '367.5 w', 'Ax + bx', '2000 m s⁻¹'],
 ['Displacement', '2 bev', 'Equation of continuity', 'Distance'],
 ['Direction', 'Random error', '-200 n', '6 rad s⁻¹'],
 ['Remain constant', 'Global pointing system', '10 ma', '200 n'],
 ['Charge', 'Attractive force', "Newton's law", 'Scalar product'],
 ['J C-1', 'M', 'Direction', 'Vector addition'],
 ['1 tv channels', 'Equation of continuity', 'Centripetal velocity', 'Nm²c-1'],
 ['Positive', '2 geo-stationary satellites', 'Viscosity', '10⁻¹2'],
 ['Ay + by', '2 types', '1.8x10⁻¹⁹ j', 'Surface of rotating space'],
 ['7.9 km s⁻¹', 'High', '2 bev', '30 m s⁻¹'],
 ['Transformer', 'Equation of continuity', 'Capacitor', 'Viscosity'],
 ['Amperes law', 'Positive', 'Different acceleration', 'Displacement'],
 ['2 geo-stationary satellites', 'Different acceleration', 'Scalar', 'Wind'],
 ['Attractive force', 'Displacement', 'A', '2000 m s⁻¹'],
 ['Viscosity', 'M', 'Random error', 'Second law'],
 ['Revolution', 'IS units', 'Second law', 'Earths mass'],
 ['30 m s⁻¹', '30 m s⁻¹', 'Displacement', 'Random error'],
 ['Force of lines', 'Ac generator', 'Vector quantities', 'Displacement'],
 ['Increases', '0.48v', 'Electrons', 'Revolution'],
 ['Positive', 'Geo-asynchronous satellites', 'Viscous', '2 types'],
 ['19 j', 'Cartesian', 'Increases', 'Velocity-speed graph'],
 ['Vector addition', 'Small', 'Increases', 'Small'],
 ['Asynchronized', 'Crumple zone', 'Displacement', 'Two'],
 ['Significant', 'Second law', 'Right hand rule', 'Inkjet printer'],
 ['Displacement', 'Zero', 'Emf', 'Angle'],
 ['Transformer', 'Angular displacement', 'Electrons', 'Force of lines'],
 ['Slightly more than collector',
  '367.5 w',
  'Laminar flow',
  'Cos⁻¹(ay + by/ax + bx)'],
 ['2.66 and 3.33', 'Centripetal velocity', '√(a² + b² + c²)', 'Micro volt'],
 ['3.3x10³', 'Vi = vf + at', 'Angular displacement', 'Repulsive'],
 ['Coal', '10 ma', 'Conserved', 'Inelastic'],
 ['Two point charges', '2as = vf² - vi²', '1 tv channels', 'Performance'],
 ['Remain same', 'Self-induction', '1 m', '30 m s⁻¹'],
 ['Linear force', '30 m s⁻¹', '900 kg m⁻³', 'Dc generator'],
 ['Physics', 'Capacitor', 'Right hand rule', 'EEG'],
 ['Two', 'Nuclear physics', 'Resistor', '(output power/input power)x100'],
 ['Cos⁻¹(ay + by/ax + bx)', 'Same', 'Same', 'Rotational kinetic energy'],
 ['Force of lines', 'Inelastic', 'Sun', 'Electrostatic'],
 ['A', '90°', 'Weight', 'A₁V₁ = A₂V₂'],
 ['Asynchronized', 'Positive direction', 'Distance', 'F = 3.14g/2r'],
 ['Base unit',
  'Equation of continuity',
  '10⁻⁶ m',
  'Law of conservation of angular velocity'],
 ['Degree per second', 'Accessible', 'Remain constant', '900 kg m⁻³'],
 ['National communication', 'Two point charges', '1240i + 1180j', 'Conserved'],
 ['1/2(vxt)',
  '900 kg m⁻³',
  'Nuclear physics',
  '(output power/input power)x100'],
 ['Massive', 'Limitation of instruments', 'Instantaneous acceleration', 'EEG'],
 ['(6i + 5j)/7.81', 'Right hand rule', 'Displacement', 'Two'],
 ['2 characteristics', 'Small', 'Transformer', 'Taking several readings'],
 ['Inkjet printer', 'Remain constant', 'Performance', '2.66 and 3.33'],
 ['Wind', 'Right hand rule', 'Paper', '(output power/input power)x100'],
 ['10²',
  '2as = vf² - vi²',
  'Multiplicative property',
  'Rectangular components'],
 ['A', 'Coal', 'Ax + bx', '57.3°'],
 ['√((ax + bx)² + (ay + by)²)',
  'Negative',
  'Rotational kinetic energy',
  'Small force'],
 ['Large gravity', 'R = 0', 'Induced emf', 'Min'],
 ['Earths mass', 'Mgf', 'Scalar quantity', 'Scalar quantity'],
 ['900 kg m⁻³', 'Laminar flow', 'Increasing', '6 rad s⁻¹'],
 ['30 m s⁻¹', 'Dc circuit', '19 j', 'Significant'],
 ['Moles', 'Vector addition', 'Cos⁻¹(ay + by/ax + bx)', '0.48v'],
 ['Laminated design', 'Impulse', 'Voltage', 'Parallel'],
 ['Flow rate', 'Limitation of instruments', 'A₁V₁ = A₂V₂', 'Emf'],
 ['Law of conservation of angular velocity',
  '2.66 and 3.33',
  'Physics',
  'Amplitude of lorenzini'],
 ['Different acceleration', 'Small', '40 n', '7.9 km s⁻¹'],
 ['Centripetal velocity', 'Stops', '(v₁ + v₂)/t', '367.5 w'],
 ['Remain same', 'Logic circuits', 'Ac generator', 'Rectangular components'],
 ['Kinetic energies', '57.3°', 'Displacement', 'Transformer'],
 ['(v₁ + v₂)/t', 'Ml⁻¹t⁻¹', 'Significant', 'Two'],
 ['Increasing', 'Remain constant', 'Kinetic energies', 'Revolution'],
 ['Viscosity', '57.3°', 'Emitter', '1/2(mv)²'],
 ['30 m s⁻¹', 'Ml⁻¹t⁻¹', '2000 m s⁻¹', 'J C-1'],
 ['9 j', 'Viscosity', 'Laminar flow', 'Dc generator'],
 ['F = 3.14g/2r', 'Linear force', 'Degree per second', 'Linear force'],
 ['A.b', 'Mgf', 'R = 0', 'Energy'],
 ['Same', 'Small', '57.3°', 'Relativity'],
 ['Cos', 'Distance', '2 characteristics', '20 times per second'],
 ['F = 3.14g/2r', '2.7 g cm⁻³', '(6i + 5j)/7.81', 'Flow rate'],
 ['Displacement', 'Random error', 'Displacement', 'Negative'],
 ['Dc generator',
  'Selected standards',
  'Velocity-speed graph',
  'T = 2vix(sin/g)'],
 ['Vector quantities', '3.3x10³', 'Viscous', 'Scalar product'],
 ['Nuclear physics', 'Min', 'Revolution', 'One minute'],
 ['Electric field', 'Moles', 'Capacitor', 'Physics'],
 ['Moles', 'Dc generator', 'Changes continuously', 'Faradays law'],
 ['Small', 'Line', 'Scalar quantity', '10 ma'],
 ['Velocity-speed graph', 'Dc circuit', 'One minute', '1/2 cv²'],
 ['Ac generator', '2 geo-stationary satellites', 'Energy', 'Physics'],
 ['200 n', 'Significant', 'Voltage', 'Selected standards'],
 ['Rod', 'Displacement', 'Viscosity', 'Conserved'],
 ['Five', 'Electric field', "Newton's law", '2 types'],
 ['J C-1', 'Distance', 'Nuclear physics', 'Random error'],
 ['1/2 cv²', '107 hz', 'Zero', 'Distance'],
 ['107 hz', 'Dc circuit', 'Viscosity', 'Ac generator'],
 ['1/2 cv²', 'IS units', '10⁻¹2', 'Weight'],
 ['0.12x10⁻² v', 'Min', 'Arbitrarily', 'Slows down'],
 ['2000 m s⁻¹', 'Ac generator', 'Small', 'Rotational kinetic energy'],
 ['Accurate', 'Moles', 'T = 2vix(sin/g)', 'Vector addition'],
 ['National communication',
  'Velocity-speed graph',
  '10²',
  'Gravitational field'],
 ['Changes continuously',
  'Cos⁻¹(ay + by/ax + bx)',
  'Frequent error',
  'Multiplicative property'],
 ['Velocity', 'Slows down', 'Inkjet printer', '10⁻⁶ m'],
 ['Increasing speed', 'A.b', 'Base unit', 'Limitation of instruments'],
 ['120 w', 'Emf', '40 n', 'Earths mass'],
 ['Scalar quantity', 'Displacement', 'Random error', 'Arbitrarily'],
 ['Nuclear physics', '1/2 cv²', '19 j', 'Viscous'],
 ['Displacement', 'Displacement', 'Moles', 'Vf = vi + 2as'],
 ['1 v', 'Emf', '1/2(vxt)', '1 tv channels'],
 ['Increasing', 'Velocity-speed graph', 'Physics', 'Laminar flow'],
 ['Earths mass',
  'Displacement',
  '(output power/input power)x100',
  'Earths mass'],
 ['N c-1', 'Distance', 'Cos', '10⁻¹2'],
 ['Angle', '90°', 'Increasing', 'Electrons'],
 ['Cartesian', '9 j', 'Revolution', 'Emf'],
 ['Bruce mccandless', '1.2041 kg m⁻³', '7.9 km s⁻¹', 'Velocity-speed graph'],
 ['7.9 km s⁻¹', '8000 kg s⁻¹', 'Moles', '1 tv channels'],
 ['1/2 cv²', 'Dc generator', '2 bev', 'National communication'],
 ['Negative', 'One minute', 'Ax + bx', 'Global pointing system'],
 ['Emf', 'Instantaneous acceleration', '2as = vf² - vi²', 'Increases'],
 ['Microwaves', 'Emf', '1.8x10⁻¹⁹ j', '10⁻² f'],
 ['N c-1', 'Slows down', 'Self-induction', '1 v'],
 ['Zero', 'Smaller diameter', "Newton's law", '1240i + 1180j'],
 ['Mass of satellite', 'Same', 'Kinetic energies', 'Flow rate'],
 ['Emitter and collector equally doped',
  'Emitter and collector equally doped',
  'Per month',
  'Geo-asynchronous satellites'],
 ['Viscosity', 'Viscosity', 'Same', 'Emf'],
 ['Resistor', 'Ilbxcosɵ', 'Displacement', 'Nm²c-1'],
 ['1/4(mv²)', 'Random error', '1/2(mv)²', 'Five'],
 ['Self-induction', '30 m s⁻¹', 'Arbitrarily', 'Selected standards'],
 ['Electrostatic',
  'Positive direction',
  'Coal',
  '(output power/input power)x100'],
 ['Physics', 'Viscosity', '√(a² + b² + c²)', 'Moles'],
 ['Laminated design', 'Paper', 'Charge', 'A₁V₁ = A₂V₂'],
 ['Degree per second', 'Increases', 'Velocity-speed graph', 'F = (-m/t)v'],
 ['Dc generator', 'Joule', 'Direction', 'Positive'],
 ['Conserved', 'Scalar product', 'Emf', 'Nuclear physics'],
 ['Viscosity', 'F = 3.14g/2r', 'Parallel', 'Significant'],
 ['Five', '30 m s⁻¹', 'Kinetic energies', 'Arbitrarily'],
 ['Distance', 'Conserved', 'Viscosity', 'Positive'],
 ['1240i + 1180j', 'Base unit', '1/2 cv²', 'Impulse'],
 ['2 geo-stationary satellites',
  'Sun',
  '(6i + 5j)/7.81',
  'Equation of continuity'],
 ['Distance', 'Emf', '10 ma', 'Positive direction'],
 ['10⁻² f', 'Vi = vf + at', 'Crumple zone', 'Second law'],
 ['Limitation of instruments',
  'Displacement',
  'Scalar quantity',
  'Work done by a constant force'],
 ['Arbitrarily',
  'Equation of continuity',
  'Rotational kinetic energy',
  '110°'],
 ['Global pointing system',
  'Cos⁻¹(ay + by/ax + bx)',
  'Crumple zone',
  'Geo-asynchronous satellites'],
 ['Resistor', 'M', 'Increases', 'Velocity-speed graph'],
 ['A', 'A', 'M', 'Displacement'],
 ['One minute', 'Direction', 'Deduce emf', 'Ax + bx'],
 ['Increases', '107 hz', 'Instantaneous acceleration', 'Upwards positive'],
 ['6.6x10⁻⁹ rad',
  'Global pointing system',
  'Different acceleration',
  'Accessible'],
 ['Angular displacement',
  'Law of conservation of angular velocity',
  'Physics',
  'Angle'],
 ['Remain constant', 'EEG', '120 w', '2 bev'],
 ['1 tv channels', 'Physics', 'Displacement', 'Joule'],
 ['Two', 'Limitation of instruments', 'Degree per second', '2 types'],
 ['Rectifier', 'Base unit', 'Voltage', 'Nm²c-1'],
 ['Diving', 'Logic circuits', 'Straight line', 'Emf'],
 ['Amperes law', '2.66 and 3.33', 'Flow rate', 'Remain constant'],
 ['9x10³', 'Instantaneous acceleration', 'Attractive force', 'Massive'],
 ['Equation of continuity', 'Centripetal velocity', 'Viscosity', 'IS units'],
 ['Electric field', 'Centripetal velocity', '10⁻¹2', 'Physics'],
 ['57.3°', '2 types', 'Positive', 'Rectifier'],
 ['Vf = vi + 2as', 'R = 0', 'Ax + bx', '1.2041 kg m⁻³'],
 ['Voltage', 'Vi = vf + at', 'Same', 'Surface of rotating space'],
 ['Diving', 'Rod', 'Small', 'Parallel'],
 ['Two', 'Emf', 'Conserved', '10⁻² f']]

In [46]:
final_wrong_options = []
for n, person in enumerate(correct_answers):
    if person in wrong_options[n]:
        wrong_options[n].remove(person)
        final_wrong_options.append(wrong_options[n])
    else:
        final_wrong_options.append(wrong_options[n][:-1])

In [17]:
final_wrong_options

[['Stops', 'Inkjet printer', 'Rectifier'],
 ['Parallel', 'National communication', 'Relativity'],
 ['Random error', 'EEG', 'Random error'],
 ['Mass of satellite', '2as = vf² - vi²', 'Parallel'],
 ['Equation of continuity', 'Emf', 'Self-induction'],
 ['Angular displacement', 'Physics', 'Cos'],
 ['Kinetic energies', 'Attractive force', 'Accurate'],
 ['Same', 'Vf = vi + 2as', 'Two'],
 ['30 m s⁻¹', '2as = vf² - vi²', '90°'],
 ['Vavg = (d/t)', 'Emf', 'One minute'],
 ['Sun', '(output power/input power)x100', 'IS units'],
 ['90°', 'Viscosity', 'Voltage'],
 ['10⁻⁶ m', '6 rad s⁻¹', 'Matter'],
 ['1.8x10⁻¹⁹ j', 'Viscosity', 'Mgf'],
 ['57.3°', 'T = 2vix(sin/g)', '1.8x10⁻¹⁹ j'],
 ['Ay + by', 'Vector quantities', 'Scalar quantity'],
 ['Massive', 'Scalar product', 'Moles'],
 ['Physics', 'Limitation of instruments', 'National communication'],
 ['Multiplicative property', 'Momentum', 'Viscous'],
 ['Smaller diameter', 'Ax + bx', '0.48v'],
 ['Scalar', '2as = vf² - vi²', 'Vavg = (d/t)'],
 ['Linear force', '0.48v', 'Remain same'],
 ['Attractive force', 'Scalar product', 'Displacement'],
 ['Six', '367.5 w', 'Impulse'],
 ['1 tv channels', 'Mid', 'Displacement'],
 ['Emf', 'Angular displacement', 'J C-1'],
 ['Degree per second', 'Moles', 'Ax + bx'],
 ['30 m s⁻¹', 'Velocity-speed graph', 'Kinetic energies'],
 ['10⁻⁶ m', 'Degree per second', 'Angular displacement'],
 ['900 kg m⁻³', 'Amplitude of lorenzini', 'Angle'],
 ["Newton's law", 'F = (-m/t)v', '2 types'],
 ['8000 kg s⁻¹', '120 w', 'Voltage'],
 ['Dc generator', 'Joule', 'Kinetic energy'],
 ['Mutual induction', 'Frequent error', 'Weight'],
 ['Kinetic energy', 'Positive direction', 'Ax + bx'],
 ['Small', '1 tv channels', 'Diving'],
 ['Random error', 'Rectangular components', 'A.b'],
 ['2 kind of units', 'Scalar quantity', 'Two point charges'],
 ['Resistor', 'Second law', 'Laminated design'],
 ['Degree per second', 'Viscosity', 'Asynchronized'],
 ['Two point charges', '8000 kg s⁻¹', 'Nuclear physics'],
 ['Amperes law', 'Gravitational field', '7.9 km s⁻¹'],
 ['Angular displacement', '10⁻⁶ m', '1/2(mv)²'],
 ['Subtraction of x-components', 'Conserved', 'Equation of continuity'],
 ['Amplitude of lorenzini', 'A.b', '1 v'],
 ['Distance', '1/4(mv²)', '10⁻⁶ m'],
 ['7.9 km s⁻¹', 'Scalar', 'Small force'],
 ['Significant', '1240i + 1180j', '40 n'],
 ['Vavg = (d/t)', 'Eyeretinography', 'Equation of continuity'],
 ['Faradays law', '(output power/input power)x100', 'Random error'],
 ['Laminated design', 'Displacement', 'Zero'],
 ['Mass of satellite', '1 m', '40 n'],
 ['-200 n', 'Direction', 'Second law'],
 ['National communication', 'A', 'Viscous'],
 ['20 times per second', 'Upwards positive', '2000 m s⁻¹'],
 ['(v₁ + v₂)/t', '2 types', 'Small'],
 ['Zero', '20 times per second', 'Limitation of instruments'],
 ['Same', 'Parallel', 'One minute'],
 ['Emf', 'Negative', 'Selected standards'],
 ['1 m', 'Equation of continuity', 'Linear force'],
 ['Remain constant', 'Micro volt', 'Emf'],
 ['Momentum', '0.12x10⁻² v', '900 kg m⁻³'],
 ['30 m s⁻¹', 'F = 3.14g/2r', 'One minute'],
 ['Direction', 'Radian', '20 times per second'],
 ['Equation of continuity', 'Mass of satellite', 'Ac generator'],
 ['Transformer', 'Weight', 'Momentum'],
 ['7.9 km s⁻¹', 'Joule', 'Five'],
 ['Laminar flow', 'Angular displacement', 'Dc generator'],
 ['8000 kg s⁻¹', 'Vector quantities', 'Direction'],
 ['Physics', 'Law of conservation of angular velocity', '2000 m s⁻¹'],
 ['Impulse', '1240i + 1180j', 'Microwaves'],
 ['367.5 w', 'Degree per second', 'Line'],
 ['Large gravity', '6 rad s⁻¹', 'Significant'],
 ['Viscous', 'R = 0', '9 j'],
 ['Subtraction of x-components', 'Positive', 'One minute'],
 ['Two', 'A₁V₁ = A₂V₂', 'Instantaneous acceleration'],
 ['Multiplicative property', 'Straight line', '2 types'],
 ['(v₁ + v₂)/t', 'Surface of rotating space', 'Random error'],
 ['Bruce mccandless', 'Resistor', 'Induced emf'],
 ['Physics', 'Base unit', 'Slows down'],
 ['Repulsive', 'Matter', 'Slightly more than collector'],
 ['6.6x10⁻⁹ rad', 'Angle', 'Electric field'],
 ['Distance', '(6i + 5j)/7.81', 'Distance'],
 ['Impulse', 'A.b', 'Revolution'],
 ['Vi = vf + at', 'Negative', 'Min'],
 ['Viscosity', 'Impulse', 'High'],
 ['Mass of satellite', 'Moles', '2 types'],
 ['Angular displacement', 'Global pointing system', 'Impulse'],
 ['19 j', '1.2041 kg m⁻³', 'Conserved'],
 ['-200 n', '20 times per second', 'Mutual induction'],
 ['2 characteristics', 'Positive', 'Displacement'],
 ['Small', 'Cartesian', '6.6x10⁻⁹ rad'],
 ['0.12x10⁻² v', 'Different acceleration', '-200 n'],
 ['107 hz', 'Random error', 'Nm²c-1'],
 ['Small force', 'F = 3.14g/2r', 'Amperes law'],
 ['Physics', 'Viscous', 'Displacement'],
 ['Performance', 'Increasing', 'Paper'],
 ['Increases', '0.12x10⁻² v', 'Accessible'],
 ['Right hand rule', 'Electrons', 'Vector addition'],
 ['Weight - drag force', 'Dc circuit', 'Scalar'],
 ['Impulse', 'Ohms law', '10⁻² f'],
 ['Impulse', 'Subtraction of x-components', 'Physics'],
 ['2000 m s⁻¹', 'Viscous', 'Asynchronized'],
 ['Moles', 'Amperes law', 'Law of conservation of angular velocity'],
 ['Geo-asynchronous satellites', 'Increasing speed', 'Ilbxcosɵ'],
 ['Mass of satellite', 'Ac generator', 'Two'],
 ['30 m s⁻¹', 'Angle', '2.7 g cm⁻³'],
 ['Weight', '30 m s⁻¹', '120 w'],
 ['Small', 'Attractive force', 'Two'],
 ['Displacement', 'Capacitor', 'Moles'],
 ['A.b', '1 v', 'Microwaves'],
 ['Degree per second', '367.5 w', 'Ax + bx'],
 ['Displacement', '2 bev', 'Equation of continuity'],
 ['Direction', 'Random error', '-200 n'],
 ['Remain constant', 'Global pointing system', '10 ma'],
 ['Charge', 'Attractive force', "Newton's law"],
 ['J C-1', 'M', 'Direction'],
 ['1 tv channels', 'Equation of continuity', 'Centripetal velocity'],
 ['Positive', '2 geo-stationary satellites', 'Viscosity'],
 ['Ay + by', '2 types', '1.8x10⁻¹⁹ j'],
 ['7.9 km s⁻¹', 'High', '2 bev'],
 ['Transformer', 'Equation of continuity', 'Capacitor'],
 ['Amperes law', 'Positive', 'Different acceleration'],
 ['2 geo-stationary satellites', 'Different acceleration', 'Scalar'],
 ['Attractive force', 'Displacement', 'A'],
 ['Viscosity', 'M', 'Random error'],
 ['Revolution', 'IS units', 'Second law'],
 ['30 m s⁻¹', '30 m s⁻¹', 'Displacement'],
 ['Force of lines', 'Ac generator', 'Vector quantities'],
 ['Increases', '0.48v', 'Electrons'],
 ['Positive', 'Geo-asynchronous satellites', 'Viscous'],
 ['19 j', 'Cartesian', 'Increases'],
 ['Vector addition', 'Small', 'Increases'],
 ['Asynchronized', 'Crumple zone', 'Displacement'],
 ['Significant', 'Second law', 'Right hand rule'],
 ['Displacement', 'Zero', 'Emf'],
 ['Transformer', 'Angular displacement', 'Electrons'],
 ['Slightly more than collector', '367.5 w', 'Laminar flow'],
 ['2.66 and 3.33', 'Centripetal velocity', '√(a² + b² + c²)'],
 ['3.3x10³', 'Vi = vf + at', 'Angular displacement'],
 ['Coal', '10 ma', 'Conserved'],
 ['Two point charges', '2as = vf² - vi²', '1 tv channels'],
 ['Remain same', 'Self-induction', '1 m'],
 ['Linear force', '30 m s⁻¹', '900 kg m⁻³'],
 ['Physics', 'Capacitor', 'Right hand rule'],
 ['Two', 'Nuclear physics', 'Resistor'],
 ['Cos⁻¹(ay + by/ax + bx)', 'Same', 'Same'],
 ['Force of lines', 'Inelastic', 'Sun'],
 ['A', '90°', 'Weight'],
 ['Asynchronized', 'Positive direction', 'Distance'],
 ['Base unit', 'Equation of continuity', '10⁻⁶ m'],
 ['Degree per second', 'Accessible', 'Remain constant'],
 ['National communication', 'Two point charges', '1240i + 1180j'],
 ['1/2(vxt)', '900 kg m⁻³', 'Nuclear physics'],
 ['Massive', 'Limitation of instruments', 'Instantaneous acceleration'],
 ['(6i + 5j)/7.81', 'Right hand rule', 'Displacement'],
 ['2 characteristics', 'Small', 'Transformer'],
 ['Inkjet printer', 'Remain constant', 'Performance'],
 ['Wind', 'Right hand rule', 'Paper'],
 ['10²', '2as = vf² - vi²', 'Multiplicative property'],
 ['A', 'Coal', 'Ax + bx'],
 ['√((ax + bx)² + (ay + by)²)', 'Negative', 'Rotational kinetic energy'],
 ['Large gravity', 'R = 0', 'Induced emf'],
 ['Earths mass', 'Mgf', 'Scalar quantity'],
 ['900 kg m⁻³', 'Laminar flow', 'Increasing'],
 ['30 m s⁻¹', 'Dc circuit', '19 j'],
 ['Moles', 'Vector addition', 'Cos⁻¹(ay + by/ax + bx)'],
 ['Laminated design', 'Impulse', 'Voltage'],
 ['Flow rate', 'Limitation of instruments', 'A₁V₁ = A₂V₂'],
 ['Law of conservation of angular velocity', '2.66 and 3.33', 'Physics'],
 ['Different acceleration', 'Small', '40 n'],
 ['Centripetal velocity', 'Stops', '(v₁ + v₂)/t'],
 ['Remain same', 'Logic circuits', 'Ac generator'],
 ['Kinetic energies', '57.3°', 'Displacement'],
 ['(v₁ + v₂)/t', 'Ml⁻¹t⁻¹', 'Significant'],
 ['Increasing', 'Remain constant', 'Kinetic energies'],
 ['Viscosity', '57.3°', 'Emitter'],
 ['Ml⁻¹t⁻¹', '2000 m s⁻¹', 'J C-1'],
 ['9 j', 'Viscosity', 'Laminar flow'],
 ['F = 3.14g/2r', 'Linear force', 'Degree per second'],
 ['A.b', 'Mgf', 'R = 0'],
 ['Same', 'Small', '57.3°'],
 ['Cos', 'Distance', '2 characteristics'],
 ['F = 3.14g/2r', '2.7 g cm⁻³', '(6i + 5j)/7.81'],
 ['Displacement', 'Random error', 'Displacement'],
 ['Dc generator', 'Selected standards', 'Velocity-speed graph'],
 ['Vector quantities', '3.3x10³', 'Viscous'],
 ['Nuclear physics', 'Min', 'Revolution'],
 ['Electric field', 'Moles', 'Capacitor'],
 ['Moles', 'Dc generator', 'Changes continuously'],
 ['Small', 'Line', 'Scalar quantity'],
 ['Velocity-speed graph', 'Dc circuit', 'One minute'],
 ['Ac generator', '2 geo-stationary satellites', 'Energy'],
 ['200 n', 'Significant', 'Voltage'],
 ['Rod', 'Displacement', 'Viscosity'],
 ['Five', 'Electric field', "Newton's law"],
 ['J C-1', 'Distance', 'Nuclear physics'],
 ['1/2 cv²', '107 hz', 'Zero'],
 ['107 hz', 'Dc circuit', 'Viscosity'],
 ['1/2 cv²', 'IS units', '10⁻¹2'],
 ['0.12x10⁻² v', 'Min', 'Arbitrarily'],
 ['2000 m s⁻¹', 'Ac generator', 'Small'],
 ['Accurate', 'Moles', 'T = 2vix(sin/g)'],
 ['National communication', 'Velocity-speed graph', '10²'],
 ['Changes continuously', 'Cos⁻¹(ay + by/ax + bx)', 'Frequent error'],
 ['Velocity', 'Slows down', 'Inkjet printer'],
 ['Increasing speed', 'A.b', 'Base unit'],
 ['120 w', 'Emf', '40 n'],
 ['Scalar quantity', 'Displacement', 'Random error'],
 ['Nuclear physics', '1/2 cv²', '19 j'],
 ['Displacement', 'Displacement', 'Moles'],
 ['1 v', 'Emf', '1/2(vxt)'],
 ['Increasing', 'Velocity-speed graph', 'Physics'],
 ['Earths mass', 'Displacement', '(output power/input power)x100'],
 ['N c-1', 'Distance', 'Cos'],
 ['Angle', '90°', 'Increasing'],
 ['Cartesian', '9 j', 'Revolution'],
 ['Bruce mccandless', '1.2041 kg m⁻³', '7.9 km s⁻¹'],
 ['7.9 km s⁻¹', '8000 kg s⁻¹', 'Moles'],
 ['1/2 cv²', 'Dc generator', '2 bev'],
 ['Negative', 'One minute', 'Ax + bx'],
 ['Emf', 'Instantaneous acceleration', '2as = vf² - vi²'],
 ['Microwaves', 'Emf', '1.8x10⁻¹⁹ j'],
 ['N c-1', 'Slows down', 'Self-induction'],
 ['Zero', 'Smaller diameter', "Newton's law"],
 ['Mass of satellite', 'Same', 'Kinetic energies'],
 ['Emitter and collector equally doped',
  'Emitter and collector equally doped',
  'Per month'],
 ['Viscosity', 'Viscosity', 'Same'],
 ['Resistor', 'Ilbxcosɵ', 'Displacement'],
 ['1/4(mv²)', 'Random error', '1/2(mv)²'],
 ['Self-induction', '30 m s⁻¹', 'Arbitrarily'],
 ['Electrostatic', 'Positive direction', 'Coal'],
 ['Physics', 'Viscosity', '√(a² + b² + c²)'],
 ['Laminated design', 'Paper', 'Charge'],
 ['Degree per second', 'Increases', 'Velocity-speed graph'],
 ['Dc generator', 'Joule', 'Direction'],
 ['Conserved', 'Scalar product', 'Emf'],
 ['Viscosity', 'F = 3.14g/2r', 'Parallel'],
 ['Five', '30 m s⁻¹', 'Kinetic energies'],
 ['Distance', 'Conserved', 'Viscosity'],
 ['1240i + 1180j', 'Base unit', '1/2 cv²'],
 ['2 geo-stationary satellites', 'Sun', '(6i + 5j)/7.81'],
 ['Distance', 'Emf', '10 ma'],
 ['10⁻² f', 'Vi = vf + at', 'Crumple zone'],
 ['Limitation of instruments', 'Displacement', 'Scalar quantity'],
 ['Arbitrarily', 'Equation of continuity', 'Rotational kinetic energy'],
 ['Global pointing system', 'Cos⁻¹(ay + by/ax + bx)', 'Crumple zone'],
 ['Resistor', 'M', 'Increases'],
 ['A', 'A', 'M'],
 ['One minute', 'Direction', 'Deduce emf'],
 ['Increases', '107 hz', 'Instantaneous acceleration'],
 ['6.6x10⁻⁹ rad', 'Global pointing system', 'Different acceleration'],
 ['Angular displacement',
  'Law of conservation of angular velocity',
  'Physics'],
 ['Remain constant', 'EEG', '120 w'],
 ['1 tv channels', 'Physics', 'Displacement'],
 ['Two', 'Limitation of instruments', 'Degree per second'],
 ['Rectifier', 'Base unit', 'Voltage'],
 ['Diving', 'Logic circuits', 'Straight line'],
 ['Amperes law', '2.66 and 3.33', 'Flow rate'],
 ['9x10³', 'Instantaneous acceleration', 'Attractive force'],
 ['Equation of continuity', 'Centripetal velocity', 'Viscosity'],
 ['Electric field', 'Centripetal velocity', '10⁻¹2'],
 ['57.3°', '2 types', 'Rectifier'],
 ['Vf = vi + 2as', 'R = 0', 'Ax + bx'],
 ['Voltage', 'Vi = vf + at', 'Same'],
 ['Diving', 'Rod', 'Small'],
 ['Two', 'Emf', 'Conserved']]

In [47]:
optionB = []
optionC = []
optionD = []
for each in final_wrong_options:
    optionB.append(each[0])
    optionC.append(each[1])
    optionD.append(each[-1])

In [20]:
len(optionB)

267

In [48]:
df['OPTION B'] = optionB
df['OPTION C'] = optionC
df['OPTION D'] = optionD

In [49]:
df

,S.N.,Question,Option A,OPTION B,OPTION C,OPTION D
0,1,Device that converts electrical energy into me...,Ac generator,1.2041 kg m⁻³,Mid,20 times per second
1,2,Alternative current generator is basically bas...,Amperes law,Right hand rule,Instantaneous acceleration,Matter
2,3,"In alternative current generator, ac current r...",20 times per second,Matter,Amplitude of lorenzini,T = 2vix(sin/g)
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,Diving,Vi = vf + at,Right hand rule
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Nm²c-1,19 j,Ax + bx
...,...,...,...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive,0.12x10⁻² v,Subtraction of x-components,Remain constant
263,264,When an object is moved in gravitational field...,Work done by a constant force,Logic circuits,Cos⁻¹(ay + by/ax + bx),Inkjet printer
264,265,System international unit of work done is newt...,Joule,Distance,Newton's law,1/2(vxt)
265,266,"If angle of work done is less than 90°, then w...",Negative,1.2041 kg m⁻³,Amplitude of lorenzini,Rectifier
266,267,Product of force and displacement is known as,Distance,Emitter,900 kg m⁻³,9 j

In [50]:

df['CORRECT ANSWER'] = np.nan
df.set_index('S.N.', inplace=True)
# df.columns = ['S.N.','QUESTION', 'OPTION A', 'OPTION B', 'OPTION C', 'OPTION D','CORRECT ANSWER']

In [56]:

# df['CORRECT ANSWER'] = np.nan
# df.set_index('S.N.', inplace=True)
df.columns = ['QUESTION', 'OPTION A', 'OPTION B', 'OPTION C', 'OPTION D','CORRECT ANSWER']
# df.columns

In [57]:
df

,QUESTION,OPTION A,OPTION B,OPTION C,OPTION D,CORRECT ANSWER
S.N.,,,,,,
1,Device that converts electrical energy into me...,Ac generator,1.2041 kg m⁻³,Mid,20 times per second,NaN
2,Alternative current generator is basically bas...,Amperes law,Right hand rule,Instantaneous acceleration,Matter,NaN
3,"In alternative current generator, ac current r...",20 times per second,Matter,Amplitude of lorenzini,T = 2vix(sin/g),NaN
4,"""a current carrying coil placed in magnetic fi...",Dc generator,Diving,Vi = vf + at,Right hand rule,NaN
5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Nm²c-1,19 j,Ax + bx,NaN
...,...,...,...,...,...,...
263,"When angle is equal to zero, work will be",Positive,0.12x10⁻² v,Subtraction of x-components,Remain constant,NaN
264,When an object is moved in gravitational field...,Work done by a constant force,Logic circuits,Cos⁻¹(ay + by/ax + bx),Inkjet printer,NaN
265,System international unit of work done is newt...,Joule,Distance,Newton's law,1/2(vxt),NaN
266,"If angle of work done is less than 90°, then w...",Negative,1.2041 kg m⁻³,Amplitude of lorenzini,Rectifier,NaN
267,Product of force and displacement is known as,Distance,Emitter,900 kg m⁻³,9 j,NaN

In [69]:
df

,S.N.,Question,Option A
0,1,Device that converts electrical energy into me...,Ac generator
1,2,Alternative current generator is basically bas...,Amperes law
2,3,"In alternative current generator, ac current r...",20 times per second
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration
...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive
263,264,When an object is moved in gravitational field...,Work done by a constant force
264,265,System international unit of work done is newt...,Joule
265,266,"If angle of work done is less than 90°, then w...",Negative
266,267,Product of force and displacement is known as,Distance

In [70]:
df['b'] = np.nan
df['c'] = np.nan
df['d'] = np.nan
df['correct'] = np.nan

In [71]:
df

,S.N.,Question,Option A,b,c,d,correct
0,1,Device that converts electrical energy into me...,Ac generator,NaN,NaN,NaN,NaN
1,2,Alternative current generator is basically bas...,Amperes law,NaN,NaN,NaN,NaN
2,3,"In alternative current generator, ac current r...",20 times per second,NaN,NaN,NaN,NaN
3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,NaN,NaN,NaN,NaN
4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
262,263,"When angle is equal to zero, work will be",Positive,NaN,NaN,NaN,NaN
263,264,When an object is moved in gravitational field...,Work done by a constant force,NaN,NaN,NaN,NaN
264,265,System international unit of work done is newt...,Joule,NaN,NaN,NaN,NaN
265,266,"If angle of work done is less than 90°, then w...",Negative,NaN,NaN,NaN,NaN
266,267,Product of force and displacement is known as,Distance,NaN,NaN,NaN,NaN

In [72]:
df.to_csv('gopalsanclean.csv')