In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [3]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

Series
A Series, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:

In [4]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

A Series is, in essence, a single column of a DataFrame. So you can assign column values to the Series the same way as before, using an index parameter. However, a Series does not have a column name, it only has one overall name

In [5]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

The pd.read_csv() function is well-endowed, with over 30 optional parameters you can specify. For example, you can see in this dataset that the CSV file has a built-in index, which pandas did not pick up on automatically. To make pandas use that column for the index (instead of creating a new one from scratch), we can specify an index_col.

In [6]:
pd.DataFrame({'apples': 50, 'banans': 34})

ValueError: If using all scalar values, you must pass an index

In [10]:
pd.DataFrame({'apples': 50, 'banans': 34}, index=[0,])

   apples  banans
0      50      34

In [11]:
pd.DataFrame({'apples': [50], 'banans': [34]})

   apples  banans
0      50      34

In [15]:
pd.Series(['4 cups', '1 cup', '2 large', '1 can'], index=['Flour', 'Milk', 'Eggs', 'Spam'],)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
dtype: object

In [16]:
a = pd.Series(['4 cups', '1 cup', '2 large', '1 can'], index=['Flour', 'Milk', 'Eggs', 'Spam'],name='Items')

In [18]:
print(a)

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Items, dtype: object

In [20]:
a.name

'Items'

In [21]:
a.index

Index(['Flour', 'Milk', 'Eggs', 'Spam'], dtype='object')

In [22]:
a

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Items, dtype: object

In [1]:
import pandas as pd
df = pd.DataFrame({'a':[1,2,3,4], 'b': [3,4,2,6], 'c': [23, 2, 5, 1], 'd': [1,32,12,22]})

In [24]:
df

   a  b   c   d
0  1  3  23   1
1  2  4   2  32
2  3  2   5  12
3  4  6   1  22

In [25]:
df.iloc[0]

a     1
b     3
c    23
d     1
Name: 0, dtype: int64

In [26]:
df.iloc[:, 0]

0    1
1    2
2    3
3    4
Name: a, dtype: int64

In [28]:
df.iloc[[1,2], 0:]

   a  b  c   d
1  2  4  2  32
2  3  2  5  12

Negative numbers can be used in selection. This will start counting forwards from the end of the values.

## first parameter is row, [second is column ]

In [29]:
df.iloc[-1]

a     4
b     6
c     1
d    22
Name: 3, dtype: int64

In [30]:
df.iloc[-2:]

   a  b  c   d
2  3  2  5  12
3  4  6  1  22

## iloc : index based selection

## loc: label based selection

In [34]:
df.iloc[0, 'a']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [35]:
df.loc[0, 'a']

1

In [36]:
df.loc[:, 'a']

0    1
1    2
2    3
3    4
Name: a, dtype: int64

In [37]:
df.a

0    1
1    2
2    3
3    4
Name: a, dtype: int64

iloc is conceptually simpler than loc because it ignores the dataset's indices. When we use iloc we treat the dataset like a big matrix (a list of lists), one that we have to index into by position. loc, by contrast, uses the information in the indices to do its work. Since your dataset usually has meaningful indices, it's usually easier to do things using loc instead.

In [38]:
df.loc[0, ['a', 'c']]

a     1
c    23
Name: 0, dtype: int64

In [2]:
df.iloc[2:4]

   a  b  c   d
2  3  2  5  12
3  4  6  1  22

In [3]:
df.loc[2:4]

   a  b  c   d
2  3  2  5  12
3  4  6  1  22

In [4]:
df[2:4]

   a  b  c   d
2  3  2  5  12
3  4  6  1  22

In [6]:
df.iloc[0:3]

   a  b   c   d
0  1  3  23   1
1  2  4   2  32
2  3  2   5  12

In [7]:
df.loc[0:3]

   a  b   c   d
0  1  3  23   1
1  2  4   2  32
2  3  2   5  12
3  4  6   1  22

iloc uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. loc, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.

In [8]:
df.loc[0, 'a':'d']

a     1
b     3
c    23
d     1
Name: 0, dtype: int64

In [9]:
df.loc[0, 'a':]

a     1
b     3
c    23
d     1
Name: 0, dtype: int64

In [11]:
df.index = ['i1', 'i2', 'i3', 'i4']

In [12]:
df

    a  b   c   d
i1  1  3  23   1
i2  2  4   2  32
i3  3  2   5  12
i4  4  6   1  22

In [13]:
df.iloc[0, 0]

1

In [14]:
df.loc['i1', 'a']

1

In [15]:
df.set_index('a')

   b   c   d
a
1  3  23   1
2  4   2  32
3  2   5  12
4  6   1  22

In [16]:
df

    a  b   c   d
i1  1  3  23   1
i2  2  4   2  32
i3  3  2   5  12
i4  4  6   1  22

In [17]:
import numpy as np
df['e'] = np.array([1,2,1,3])

In [18]:
df

    a  b   c   d  e
i1  1  3  23   1  1
i2  2  4   2  32  2
i3  3  2   5  12  1
i4  4  6   1  22  3

In [20]:
df['e'] == 1

i1     True
i2    False
i3     True
i4    False
Name: e, dtype: bool

This operation produced a Series of True/False booleans based on the country of each record. This result can then be used inside of loc to select the relevant data:

In [21]:
df.loc[df['e']==1]

    a  b   c   d  e
i1  1  3  23   1  1
i3  3  2   5  12  1

In [23]:
df.loc[(df['e']==1) & (df.c >10)]

    a  b   c  d  e
i1  1  3  23  1  1

In [24]:
df.loc[(df['e']==1) | (df.c >10)]

    a  b   c   d  e
i1  1  3  23   1  1
i3  3  2   5  12  1

Pandas comes with a few built-in conditional selectors, two of which we will highlight here.

The first is isin. isin is lets you select data whose value "is in" a list of values.

In [29]:
df.loc[df.a.isin([1,3])]

    a  b   c   d  e
i1  1  3  23   1  1
i3  3  2   5  12  1

The second is isnull (and its companion notnull). These methods let you highlight values which are (or are not) empty (NaN).

In [31]:
df.isnull()

        a      b      c      d      e
i1  False  False  False  False  False
i2  False  False  False  False  False
i3  False  False  False  False  False
i4  False  False  False  False  False

In [33]:
df.notnull()

       a     b     c     d     e
i1  True  True  True  True  True
i2  True  True  True  True  True
i3  True  True  True  True  True
i4  True  True  True  True  True

In [34]:
df.isna()

        a      b      c      d      e
i1  False  False  False  False  False
i2  False  False  False  False  False
i3  False  False  False  False  False
i4  False  False  False  False  False

In [35]:
import numpy as np

df.loc['i3', 'b'] = np.nan

In [36]:
df.isnull()

        a      b      c      d      e
i1  False  False  False  False  False
i2  False  False  False  False  False
i3  False   True  False  False  False
i4  False  False  False  False  False

In [37]:
df.isna()

        a      b      c      d      e
i1  False  False  False  False  False
i2  False  False  False  False  False
i3  False   True  False  False  False
i4  False  False  False  False  False

In [38]:
df.notna()

       a      b     c     d     e
i1  True   True  True  True  True
i2  True   True  True  True  True
i3  True  False  True  True  True
i4  True   True  True  True  True

In [39]:
df.notnull()

       a      b     c     d     e
i1  True   True  True  True  True
i2  True   True  True  True  True
i3  True  False  True  True  True
i4  True   True  True  True  True

In [2]:
df = pd.read_csv('datas/melb_data.csv')

In [4]:
df.Price.describe()

count    1.358000e+04
mean     1.075684e+06
std      6.393107e+05
min      8.500000e+04
25%      6.500000e+05
50%      9.030000e+05
75%      1.330000e+06
max      9.000000e+06
Name: Price, dtype: float64

In [6]:
df.SellerG.describe()

count      13580
unique       268
top       Nelson
freq        1565
Name: SellerG, dtype: object

In [7]:
df.Price.mean()

1075684.079455081

In [8]:
df.Price.unique()

array([1480000., 1035000., 1465000., ..., 1288000., 1263500., 1323000.])

In [9]:
df.SellerG.value_counts()

Nelson           1565
Jellis           1316
hockingstuart    1167
Barry            1011
Ray               701
                 ...
Darras              1
Mitchell            1
North               1
Xynergy             1
Roger               1
Name: SellerG, Length: 268, dtype: int64

In [10]:
mean = df.Price.mean()

df.Price.map(lambda x: x-mean)

0        4.043159e+05
1       -4.068408e+04
2        3.893159e+05
3       -2.256841e+05
4        5.243159e+05
             ...
13575    1.693159e+05
13576   -4.468408e+04
13577    9.431592e+04
13578    1.424316e+06
13579    2.093159e+05
Name: Price, Length: 13580, dtype: float64

In [11]:
def divide_by_10000(x):
    return x/10000

In [12]:
df.Price.apply(divide_by_10000)

0        148.0
1        103.5
2        146.5
3         85.0
4        160.0
         ...
13575    124.5
13576    103.1
13577    117.0
13578    250.0
13579    128.5
Name: Price, Length: 13580, dtype: float64

In [14]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [15]:
df[['Rooms', 'Price', 'BuildingArea']].apply(divide_by_10000)

        Rooms  Price  BuildingArea
0      0.0002  148.0           NaN
1      0.0002  103.5        0.0079
2      0.0003  146.5        0.0150
3      0.0003   85.0           NaN
4      0.0004  160.0        0.0142
...       ...    ...           ...
13575  0.0004  124.5           NaN
13576  0.0003  103.1        0.0133
13577  0.0003  117.0           NaN
13578  0.0004  250.0        0.0157
13579  0.0004  128.5        0.0112

[13580 rows x 3 columns]

In [16]:
df[['Rooms', 'Price', 'BuildingArea']].apply(divide_by_10000, axis='rows')

        Rooms  Price  BuildingArea
0      0.0002  148.0           NaN
1      0.0002  103.5        0.0079
2      0.0003  146.5        0.0150
3      0.0003   85.0           NaN
4      0.0004  160.0        0.0142
...       ...    ...           ...
13575  0.0004  124.5           NaN
13576  0.0003  103.1        0.0133
13577  0.0003  117.0           NaN
13578  0.0004  250.0        0.0157
13579  0.0004  128.5        0.0112

[13580 rows x 3 columns]

In [17]:
df[['Rooms', 'Price', 'BuildingArea']].apply(divide_by_10000, axis='columns')

        Rooms  Price  BuildingArea
0      0.0002  148.0           NaN
1      0.0002  103.5        0.0079
2      0.0003  146.5        0.0150
3      0.0003   85.0           NaN
4      0.0004  160.0        0.0142
...       ...    ...           ...
13575  0.0004  124.5           NaN
13576  0.0003  103.1        0.0133
13577  0.0003  117.0           NaN
13578  0.0004  250.0        0.0157
13579  0.0004  128.5        0.0112

[13580 rows x 3 columns]

In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('datas/melb_data.csv')

In [4]:
df['Rooms'].astype('category')

0        2
1        2
2        3
3        3
4        4
        ..
13575    4
13576    3
13577    3
13578    4
13579    4
Name: Rooms, Length: 13580, dtype: category
Categories (9, int64): [1, 2, 3, 4, ..., 6, 7, 8, 10]

In [11]:
mask1 = df['Rooms'] == 4
mask2 = df['Price'] > 100000

In [12]:
df[mask1].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.8073,144.9952,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.7994,144.9965,Northern Metropolitan,4019.0
46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,...,1.0,2.0,597.0,127.0,NaN,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464.0
63,Airport West,6 Kittyhawk St,4,h,773000.0,S,Brad,17/09/2016,13.5,3042.0,...,3.0,4.0,531.0,309.0,1980.0,Moonee Valley,-37.7263,144.8679,Western Metropolitan,3464.0

In [14]:
df[mask2].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [16]:
df[mask1&mask2].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.8073,144.9952,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.7994,144.9965,Northern Metropolitan,4019.0
46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,...,1.0,2.0,597.0,127.0,NaN,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464.0
63,Airport West,6 Kittyhawk St,4,h,773000.0,S,Brad,17/09/2016,13.5,3042.0,...,3.0,4.0,531.0,309.0,1980.0,Moonee Valley,-37.7263,144.8679,Western Metropolitan,3464.0

In [20]:
df[df['Rooms'] == 3].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.8085,144.9964,Northern Metropolitan,4019.0
16,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,2.0,1.0,113.0,110.0,1880.0,Yarra,-37.8056,144.9930,Northern Metropolitan,4019.0

In [29]:
df[df['Rooms']==4 & df['Price']<=150000].head()

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

In [30]:
df[(df['Rooms']==4) & (df['Price']<=150000)].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1805,Caulfield,30 Pyne St,4,h,131000.0,PI,Rodney,25/02/2017,8.9,3162.0,...,1.0,2.0,499.0,155.0,1920.0,Glen Eira,-37.8864,145.0242,Southern Metropolitan,2379.0
1927,Coburg,171 Moreland Rd,4,h,145000.0,PI,Jellis,4/06/2016,7.8,3058.0,...,1.0,1.0,536.0,164.0,1910.0,Moreland,-37.7555,144.9658,Northern Metropolitan,11204.0

In [31]:
mask1

0        False
1        False
2        False
3        False
4         True
         ...
13575     True
13576    False
13577    False
13578     True
13579     True
Name: Rooms, Length: 13580, dtype: bool

In [32]:
mask2

0        True
1        True
2        True
3        True
4        True
         ...
13575    True
13576    True
13577    True
13578    True
13579    True
Name: Price, Length: 13580, dtype: bool

In [33]:
mask3 = df['Landsize'] >400

In [38]:
df[mask1&(mask2|mask3)].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.8073,144.9952,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.7994,144.9965,Northern Metropolitan,4019.0
46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,...,1.0,2.0,597.0,127.0,NaN,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464.0
63,Airport West,6 Kittyhawk St,4,h,773000.0,S,Brad,17/09/2016,13.5,3042.0,...,3.0,4.0,531.0,309.0,1980.0,Moonee Valley,-37.7263,144.8679,Western Metropolitan,3464.0

returns true if the list of values are present in dataframe

In [47]:
df.isin([4,'Airport West', 'Collins', 1])

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13576,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13577,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
13578,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
13579,False,False,True,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False

In [48]:
df.isnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
13576,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13577,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
13578,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13579,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [49]:
df.notna()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13576,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13577,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13578,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13579,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True

In [50]:
df.notnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13576,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13577,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13578,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13579,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True

In [52]:
df[df.notnull()].shape

(13580, 21)

In [53]:
df.shape

(13580, 21)

In [56]:
df[df.notna()].shape

(13580, 21)

In [4]:
df['Rooms'].between(3,5).head()

0    False
1    False
2     True
3     True
4     True
Name: Rooms, dtype: bool

In [5]:
df['Rooms'].duplicated()

0        False
1         True
2        False
3         True
4        False
         ...
13575     True
13576     True
13577     True
13578     True
13579     True
Name: Rooms, Length: 13580, dtype: bool

In [6]:
a = df['Rooms']

In [12]:
a.drop_duplicates().size

9

In [11]:
a.size

13580

In [14]:
a.unique()

array([ 2,  3,  4,  1,  6,  5,  8,  7, 10])

In [15]:
a.nunique()

9

In [17]:
df['Price'].unique()

array([1480000., 1035000., 1465000., ..., 1288000., 1263500., 1323000.])

In [19]:
df['Price'].unique().shape

(2204,)

In [21]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [22]:
df.tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [23]:
df.index

RangeIndex(start=0, stop=13580, step=1)

In [25]:
d1 = df[['Landsize', 'Rooms', 'Address', 'Price']]

In [27]:
d1.head()

   Landsize  Rooms           Address      Price
0     202.0      2      85 Turner St  1480000.0
1     156.0      2   25 Bloomburg St  1035000.0
2     134.0      3      5 Charles St  1465000.0
3      94.0      3  40 Federation La   850000.0
4     120.0      4       55a Park St  1600000.0

In [29]:
d1.dropna()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
d1.columns

Index(['Landsize', 'Rooms', 'Address', 'Price'], dtype='object')

In [32]:
df.set_index('Rooms', inplace=True)

In [33]:
df.head()

,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
Rooms,,,,,,,,,,,,,,,,,,,,
2,Abbotsford,85 Turner St,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,5 Charles St,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [34]:
df.reset_index(inplace=True)

In [35]:
df.head()

,Rooms,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,2,Abbotsford,85 Turner St,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,3,Abbotsford,5 Charles St,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [39]:
df.loc[0, 'Rooms']

2

In [42]:
df.loc[: 4]

,Rooms,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,2,Abbotsford,85 Turner St,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,3,Abbotsford,5 Charles St,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [48]:

df.loc[[0,1,4]]

,Rooms,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,2,Abbotsford,85 Turner St,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
4,4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [49]:
1 in df.index

True

In [54]:
df.iloc[0, 0]

2

In [56]:
df.iloc[0,10]

2.0

In [57]:
df.iloc[:, 2:5]

                Address Type      Price
0          85 Turner St    h  1480000.0
1       25 Bloomburg St    h  1035000.0
2          5 Charles St    h  1465000.0
3      40 Federation La    h   850000.0
4           55a Park St    h  1600000.0
...                 ...  ...        ...
13575      12 Strada Cr    h  1245000.0
13576     77 Merrett Dr    h  1031000.0
13577       83 Power St    h  1170000.0
13578      96 Verdon St    h  2500000.0
13579        6 Agnes St    h  1285000.0

[13580 rows x 3 columns]

In [58]:
df.iloc[3:]

,Rooms,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
3,3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
5,2,Abbotsford,129 Charles St,h,941000.0,S,Jellis,7/05/2016,2.5,3067.0,...,1.0,0.0,181.0,NaN,NaN,Yarra,-37.80410,144.99530,Northern Metropolitan,4019.0
6,3,Abbotsford,124 Yarra St,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.80240,144.99930,Northern Metropolitan,4019.0
7,2,Abbotsford,98 Charles St,h,1636000.0,S,Nelson,8/10/2016,2.5,3067.0,...,1.0,2.0,256.0,107.0,1890.0,Yarra,-37.80600,144.99540,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,4,Wheelers Hill,12 Strada Cr,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,3,Williamstown,77 Merrett Dr,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,3,Williamstown,83 Power St,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,4,Williamstown,96 Verdon St,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,4,Yarraville,6 Agnes St,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [60]:
df.iloc[[2,3,4]]

,Rooms,Suburb,Address,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2,3,Abbotsford,5 Charles St,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,3,Abbotsford,40 Federation La,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,4,Abbotsford,55a Park St,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [61]:
df.iloc[[2,3,4], 3:6]

  Type      Price Method
2    h  1465000.0     SP
3    h   850000.0     PI
4    h  1600000.0     VB

In [62]:
df.at[0, 'Price']

1480000.0

In [63]:
df.iat[0, 4]

1480000.0

In [ ]:
df.ix[]

In [5]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [9]:
df.drop(labels=['Suburb', 'Address', 'Rooms', 'Type', 'Method', 'SellerG'], axis=1, inplace=True)

,Price,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1480000.0,3/12/2016,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,1035000.0,4/02/2016,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,1465000.0,4/03/2017,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,850000.0,4/03/2017,2.5,3067.0,3.0,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,1600000.0,4/06/2016,2.5,3067.0,3.0,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,1245000.0,26/08/2017,16.7,3150.0,4.0,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,1031000.0,26/08/2017,6.8,3016.0,3.0,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,1170000.0,26/08/2017,6.8,3016.0,3.0,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,2500000.0,26/08/2017,6.8,3016.0,4.0,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,1285000.0,26/08/2017,6.3,3013.0,4.0,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [18]:
df.nsmallest(3, 'Price')

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2652,Footscray,202/51 Gordon St,1,u,85000.0,PI,Burnham,3/09/2016,6.4,3011.0,...,1.0,0.0,0.0,NaN,2007.0,Maribyrnong,-37.7911,144.8900,Western Metropolitan,7570.0
1805,Caulfield,30 Pyne St,4,h,131000.0,PI,Rodney,25/02/2017,8.9,3162.0,...,1.0,2.0,499.0,155.0,1920.0,Glen Eira,-37.8864,145.0242,Southern Metropolitan,2379.0
1927,Coburg,171 Moreland Rd,4,h,145000.0,PI,Jellis,4/06/2016,7.8,3058.0,...,1.0,1.0,536.0,164.0,1910.0,Moreland,-37.7555,144.9658,Northern Metropolitan,11204.0

In [19]:
df.nlargest(4, 'Rooms')

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
11304,Bundoora,5 Ball Ct,10,h,900000.0,PI,Ray,15/07/2017,12.1,3083.0,...,3.0,2.0,313.0,NaN,2006.0,Darebin,-37.71098,145.05381,Northern Metropolitan,10175.0
379,Ashburton,115 Ashburn Gr,8,h,2950000.0,S,hockingstuart,10/09/2016,11.0,3147.0,...,7.0,4.0,1472.0,618.0,2009.0,Boroondara,-37.87290,145.07880,Southern Metropolitan,3052.0
1926,Coburg,35 The Grove,8,u,2250000.0,PI,Peter,4/03/2017,7.8,3058.0,...,2.0,4.0,983.0,NaN,NaN,Moreland,-37.75170,144.96990,Northern Metropolitan,11204.0
3255,Heidelberg Heights,478 Waterdale Rd,8,h,770000.0,VB,Miles,19/11/2016,10.5,3081.0,...,4.0,4.0,638.0,115.0,1960.0,Banyule,-37.74260,145.04800,Eastern Metropolitan,2947.0

In [21]:
df.sample(n=3, axis=0)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4325,Niddrie,142 Hotham Rd,2,u,522500.0,SP,Nelson,26/07/2016,11.2,3042.0,...,1.0,1.0,167.0,NaN,NaN,Moonee Valley,-37.73280,144.8764,Western Metropolitan,2291.0
3552,Kensington,51 Gatehouse Dr,3,h,1000000.0,SP,Nelson,19/11/2016,4.2,3031.0,...,2.0,2.0,211.0,132.0,1997.0,Melbourne,-37.79260,144.9197,Northern Metropolitan,5263.0
11315,Chadstone,1/3 Evans St,3,u,960000.0,S,Jellis,15/07/2017,11.7,3148.0,...,2.0,2.0,382.0,151.0,2000.0,Monash,-37.88304,145.0969,Southern Metropolitan,3582.0

In [22]:
df.sample(n=3, axis=1)

       Bathroom           Address Type
0           1.0      85 Turner St    h
1           1.0   25 Bloomburg St    h
2           2.0      5 Charles St    h
3           2.0  40 Federation La    h
4           1.0       55a Park St    h
...         ...               ...  ...
13575       2.0      12 Strada Cr    h
13576       2.0     77 Merrett Dr    h
13577       2.0       83 Power St    h
13578       1.0      96 Verdon St    h
13579       1.0        6 Agnes St    h

[13580 rows x 3 columns]

In [26]:
df['Price'].dropna(df['Price'].where(df['Price']==85000))

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().