In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('datas/melb_data.csv')

In [4]:
df['Rooms'].astype('category')

0        2
1        2
2        3
3        3
4        4
        ..
13575    4
13576    3
13577    3
13578    4
13579    4
Name: Rooms, Length: 13580, dtype: category
Categories (9, int64): [1, 2, 3, 4, ..., 6, 7, 8, 10]

In [11]:
mask1 = df['Rooms'] == 4
mask2 = df['Price'] > 100000

In [12]:
df[mask1].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.8073,144.9952,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.7994,144.9965,Northern Metropolitan,4019.0
46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,...,1.0,2.0,597.0,127.0,NaN,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464.0
63,Airport West,6 Kittyhawk St,4,h,773000.0,S,Brad,17/09/2016,13.5,3042.0,...,3.0,4.0,531.0,309.0,1980.0,Moonee Valley,-37.7263,144.8679,Western Metropolitan,3464.0

In [14]:
df[mask2].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [16]:
df[mask1&mask2].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.8073,144.9952,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.7994,144.9965,Northern Metropolitan,4019.0
46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,...,1.0,2.0,597.0,127.0,NaN,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464.0
63,Airport West,6 Kittyhawk St,4,h,773000.0,S,Brad,17/09/2016,13.5,3042.0,...,3.0,4.0,531.0,309.0,1980.0,Moonee Valley,-37.7263,144.8679,Western Metropolitan,3464.0

In [20]:
df[df['Rooms'] == 3].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
6,Abbotsford,124 Yarra St,3,h,1876000.0,S,Nelson,7/05/2016,2.5,3067.0,...,2.0,0.0,245.0,210.0,1910.0,Yarra,-37.8024,144.9993,Northern Metropolitan,4019.0
11,Abbotsford,40 Nicholson St,3,h,1350000.0,VB,Nelson,12/11/2016,2.5,3067.0,...,2.0,2.0,214.0,190.0,2005.0,Yarra,-37.8085,144.9964,Northern Metropolitan,4019.0
16,Abbotsford,42 Henry St,3,h,1200000.0,S,Jellis,16/07/2016,2.5,3067.0,...,2.0,1.0,113.0,110.0,1880.0,Yarra,-37.8056,144.9930,Northern Metropolitan,4019.0

In [29]:
df[df['Rooms']==4 & df['Price']<=150000].head()

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

In [30]:
df[(df['Rooms']==4) & (df['Price']<=150000)].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
1805,Caulfield,30 Pyne St,4,h,131000.0,PI,Rodney,25/02/2017,8.9,3162.0,...,1.0,2.0,499.0,155.0,1920.0,Glen Eira,-37.8864,145.0242,Southern Metropolitan,2379.0
1927,Coburg,171 Moreland Rd,4,h,145000.0,PI,Jellis,4/06/2016,7.8,3058.0,...,1.0,1.0,536.0,164.0,1910.0,Moreland,-37.7555,144.9658,Northern Metropolitan,11204.0

In [31]:
mask1

0        False
1        False
2        False
3        False
4         True
         ...
13575     True
13576    False
13577    False
13578     True
13579     True
Name: Rooms, Length: 13580, dtype: bool

In [32]:
mask2

0        True
1        True
2        True
3        True
4        True
         ...
13575    True
13576    True
13577    True
13578    True
13579    True
Name: Price, Length: 13580, dtype: bool

In [33]:
mask3 = df['Landsize'] >400

In [38]:
df[mask1&(mask2|mask3)].head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0
20,Abbotsford,3/72 Charles St,4,h,1330000.0,PI,Kay,18/03/2017,2.5,3067.0,...,2.0,2.0,780.0,135.0,1900.0,Yarra,-37.8073,144.9952,Northern Metropolitan,4019.0
30,Abbotsford,31 Turner St,4,h,1542000.0,S,Collins,24/09/2016,2.5,3067.0,...,3.0,1.0,0.0,NaN,NaN,Yarra,-37.7994,144.9965,Northern Metropolitan,4019.0
46,Airport West,36 Roberts Rd,4,h,785000.0,S,Considine,6/08/2016,13.5,3042.0,...,1.0,2.0,597.0,127.0,NaN,Moonee Valley,-37.7259,144.8792,Western Metropolitan,3464.0
63,Airport West,6 Kittyhawk St,4,h,773000.0,S,Brad,17/09/2016,13.5,3042.0,...,3.0,4.0,531.0,309.0,1980.0,Moonee Valley,-37.7263,144.8679,Western Metropolitan,3464.0

returns true if the list of values are present in dataframe

In [47]:
df.isin([4,'Airport West', 'Collins', 1])

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13576,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13577,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
13578,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
13579,False,False,True,False,False,False,False,False,False,False,...,True,True,False,False,False,False,False,False,False,False

In [48]:
df.isnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
13576,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13577,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,True,False,False,False,False
13578,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
13579,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [49]:
df.notna()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13576,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13577,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13578,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13579,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True

In [50]:
df.notnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,False,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13576,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13577,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,False,True,True,True,True
13578,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True
13579,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,False,True,True,True,True

In [52]:
df[df.notnull()].shape

(13580, 21)

In [53]:
df.shape

(13580, 21)

In [56]:
df[df.notna()].shape

(13580, 21)