In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('datas/train_and_test2.csv')

In [3]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [2]:
df = pd.read_csv('datas/diabetes2.csv')
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [3]:
theta = np.array([0,0,0,0, 0, 0, 0, 0, 0])

In [4]:
features = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

In [7]:
X = df[features].copy()

In [8]:
X.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31

In [9]:
y = df['Outcome'].copy()

In [10]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [11]:
y.shape

(768,)

In [12]:
X.shape

(768, 8)

In [13]:
theta.shape

(9,)

X = (X.values)

In [18]:
ones = pd.Series(np.ones(X.shape[0]))

In [19]:
ones.shape

(768,)

In [23]:
X = pd.concat([ones, X], axis=1)

In [27]:
X.columns

Index([                         0,              'Pregnancies',
                        'Glucose',            'BloodPressure',
                  'SkinThickness',                  'Insulin',
                            'BMI', 'DiabetesPedigreeFunction',
                            'Age'],
      dtype='object')

In [30]:
theta.shape

(9,)

In [31]:
X.shape

(768, 9)

In [35]:
theta[0] = 1
theta[2] = 1

In [38]:
(theta*X).sum(axis=1)

0      149.0
1       86.0
2      184.0
3       90.0
4      138.0
       ...
763    102.0
764    123.0
765    122.0
766    127.0
767     94.0
Length: 768, dtype: float64

In [39]:
theta = np.array([0,0,0,0, 0, 0, 0, 0, 0])

h0 = (theta*X).sum(axis=1)

In [44]:

np.exp(np.arange(4).reshape(2,2))

array([[ 1.        ,  2.71828183],
       [ 7.3890561 , 20.08553692]])

(-1)*(h0.values)

In [59]:
h = (1/(1+(np.exp(((-1)*(h0.values))))))

In [70]:
cost = (-y)*np.log(h) -((1-y)*np.log(1-h))

In [68]:
m = X.shape[0]

In [71]:
(1/m)*(cost.sum())

0.6931471805599452

In [73]:
h.shape

(768,)

In [75]:
cost_matrix = []
alpha = 0.00000001
theta = np.array([10,20,0,1, 10, 11, 20, 10, 10])
for i in range(200):
    h0 = (theta*X).sum(axis=1)
    h = (1/(1+(np.exp(((-1)*(h0.values))))))
    print(theta)
    cost0 = (-y)*np.log(h) -((1-y)*np.log(1-h))
    cost = (1/m)*(cost0.sum())
    print(cost)
    cost_matrix.append(cost)
    for j in range(theta.shape[0]):
        theta[j] = theta[j] - (alpha*(1/m)*((h-y)*X.iloc[:, j]).sum())

[10 20  0  1 10 11 20 10 10]
inf
[ 9 19  0  0  9 10 19  9  9]
inf
[ 8 18  0  0  8  9 18  8  8]
inf
[ 7 17  0  0  7  8 17  7  7]
inf
[ 6 16  0  0  6  7 16  6  6]
inf
[ 5 15  0  0  5  6 15  5  5]
inf
[ 4 14  0  0  4  5 14  4  4]
inf
[ 3 13  0  0  3  4 13  3  3]
inf
[ 2 12  0  0  2  3 12  2  2]
inf
[ 1 11  0  0  1  2 11  1  1]
inf
[ 0 10  0  0  0  1 10  0  0]
inf
[0 9 0 0 0 0 9 0 0]
inf
[0 8 0 0 0 0 8 0 0]
inf
[0 7 0 0 0 0 7 0 0]
inf
[0 6 0 0 0 0 6 0 0]

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log

inf
[0 5 0 0 0 0 5 0 0]
inf
[0 4 0 0 0 0 4 0 0]
inf
[0 3 0 0 0 0 3 0 0]
inf
[0 2 0 0 0 0 2 0 0]
inf
[0 1 0 0 0 0 1 0 0]
inf
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452
[0 0 0 0 0 0 0 0 0]
0.6931471805599452