In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('datas/class11datacollection.csv')

In [5]:
def test(q):
    return True

In [10]:
test_data = df.apply(test, axis=0)

In [11]:
test_data

Unnamed: 0        True
S.N.              True
Question          True
Option A          True
Option B          True
Option C          True
Option D          True
Correct Option    True
dtype: bool

In [14]:
test_data = df.apply(test, axis=1)

In [15]:
test_data

0      True
1      True
2      True
3      True
4      True
       ...
262    True
263    True
264    True
265    True
266    True
Length: 267, dtype: bool

In [65]:
def test_2(q):
#     print(q)
#     print(q[0])
#     print(q.columns)
    print('--------')
#     print(q['Question'])
    return q
#     return q['Question']+'...'

In [28]:
data = pd.concat([df['Question'], test_data], axis=1)

In [32]:
data.columns

Index(['Question', 0], dtype='object')

In [67]:
ans = data.apply(test_2, axis=0)

Device that converts electrical energy into mechanical energy is
--------
Device that converts electrical energy into mechanical energy is
--------
True
--------

In [53]:
ans.columns

Index(['Question', 0], dtype='object')

In [57]:
ans['Question']

0      Device that converts electrical energy into me...
1      Alternative current generator is basically bas...
2      In alternative current generator, ac current r...
3      "a current carrying coil placed in magnetic fi...
4      At a particular instant, acceleration of a bod...
                             ...
262            When angle is equal to zero, work will be
263    When an object is moved in gravitational field...
264    System international unit of work done is newt...
265    If angle of work done is less than 90°, then w...
266        Product of force and displacement is known as
Name: Question, Length: 267, dtype: object

In [68]:
ans

                                              Question     0
0    Device that converts electrical energy into me...  True
1    Alternative current generator is basically bas...  True
2    In alternative current generator, ac current r...  True
3    "a current carrying coil placed in magnetic fi...  True
4    At a particular instant, acceleration of a bod...  True
..                                                 ...   ...
262          When angle is equal to zero, work will be  True
263  When an object is moved in gravitational field...  True
264  System international unit of work done is newt...  True
265  If angle of work done is less than 90°, then w...  True
266      Product of force and displacement is known as  True

[267 rows x 2 columns]

In [71]:
ans.columns = 'questions', 'checker'

In [79]:
ans

                                             questions  checker
0    Device that converts electrical energy into me...     True
1    Alternative current generator is basically bas...     True
2    In alternative current generator, ac current r...     True
3    "a current carrying coil placed in magnetic fi...     True
4    At a particular instant, acceleration of a bod...     True
..                                                 ...      ...
262          When angle is equal to zero, work will be     True
263  When an object is moved in gravitational field...     True
264  System international unit of work done is newt...     True
265  If angle of work done is less than 90°, then w...     True
266      Product of force and displacement is known as     True

[267 rows x 2 columns]

In [84]:
def test2(q):
    print(q[0])
    print('----------------------')
    return q

In [85]:
ans.apply(test2, axis=1)

Device that converts electrical energy into mechanical energy is
----------------------
Device that converts electrical energy into mechanical energy is
----------------------
Alternative current generator is basically based upon
----------------------
In alternative current generator, ac current reverses its direction
----------------------
"a current carrying coil placed in magnetic field experiences force", device that proves this law is
----------------------
At a particular instant, acceleration of a body is called
----------------------
Rate of change of velocity of body is represented as
----------------------
Rate of change of velocity of body is said to be
----------------------
Acceleration produced in a body is the
----------------------
In system international, angular acceleration is measured in
----------------------
Rate at which angular velocity changes with time is called
----------------------
When axis of rotation is fixed, angular velocity is considered as
----------------------
Linear equations of motion are
----------------------
In a spaceship, objects revolving around earth appears to be
----------------------
In a circular motion, direction of motion
----------------------
First linear equation of motion is represented as
----------------------
Angular displacement is defined by units
----------------------
One radian is equal to angle of
----------------------
One revolution is equal to angle of
----------------------
For very small values of angles, angular displacement is
----------------------
In system international, angular velocity is measured in
----------------------
Revolution per minute is system international unit of the
----------------------
Rate at which angular displacement changes with time is called
----------------------
Venturi relation is one of applications of
----------------------
Density of aluminum is round about equal to
----------------------
Torricelli's theorem is one of applications of
----------------------
According to bernoulli's equation, where speed is high, pressure will be
----------------------
To provide artificial gravity to spaceship, frequency needed is
----------------------
In rotating space to keep a body moving in a circular path centripetal force is provided by the
----------------------
Gravity created by some source is called
----------------------
Gps that tracks location is an abbreviation of
----------------------
Minimum velocity to put a satellite into orbital motion is
----------------------
Chimney works best on principle of
----------------------
Change in potential energy is measured as difference of
----------------------
Density of air is round about equal to
----------------------
Fundamental equation that relates pressure to fluid's speed and height is known as
----------------------
Change in kinetic energy is measured as difference of
----------------------
Energy in a capacitor can be stored in form of
----------------------
Device that is used to store charge, is named as
----------------------
1 µf of capacitance is equal to
----------------------
Capacitor is used to store electric
----------------------
Ability of capacitor to store charge is measured as its
----------------------
Force that bends straight path of object into circular path is known as
----------------------
Two cylinders of equal masses, one will have a greater rotational inertia if it has
----------------------
Curved flights at high speed requires centripetal force that is
----------------------
Centripetal force has same direction as the
----------------------
1 ghz of frequency is equal to
----------------------
Rays that travel in a narrow beam and easily pass through atmosphere of earth are
----------------------
A satellite covers longitude of earth up to
----------------------
Whole world can be covered with
----------------------
Intelsat iv telecommunication satellite has a capacity of handling
----------------------
Total energy of a body is sum of
----------------------
A nonrenewable energy is
----------------------
"energy can neither be created nor be destroyed, but it can be changed from one form to another", this law is known as
----------------------
Source of geothermal energy is
----------------------
One of energies that is known as renewable energy is
----------------------
Law stating that "force is directly proportional to product of charges and inversely proportional to square of separation between them" is called
----------------------
Two positive charges q1 = 16 c and q2 = 4 c, separated by a diameter of 3 m will produce force of
----------------------
Formula that describes statement of coulomb's law is
----------------------
Value of constant k in coulomb's law has value of
----------------------
Electric charges under action of electric forces is called
----------------------
Cross product of two vectors is represented by
----------------------
Magnitude of displacement from initial position to final position is the
----------------------
Change from initial position to final position is called
----------------------
When a body moves from one position to another change is called
----------------------
Equation d = r2-r1 is referred to as body's
----------------------
When no kinetic energy is lost, collision is said to be
----------------------
Inelastic collision is collision in which kinetic energy is
----------------------
Elastic collision is collision in which kinetic energy is
----------------------
Gravitational and electric forces are inversely proportional to
----------------------
Gravitational force is force that is always
----------------------
Electric force between two charges is similar to gravitational force between
----------------------
Printer that uses electric charges is called
----------------------
In region of any positive point charge, other positive point charge feels
----------------------
Electric field lines exerting force on a charge are also known as
----------------------
In inkjet printer, net charges are diverted by deflection plates towards
----------------------
Map of electric field lines provides information of electric fields'
----------------------
Flux will be minimum when electric field lines to area are
----------------------
Number of field lines passing at certain area are known as
----------------------
System international unit of electric flux is
----------------------
If electric field lines are parallel to area, electric flux will be
----------------------
Shark can detect potential difference of its prey up to sensitivity of
----------------------
For detecting abnormal behavior of brain, technique used is
----------------------
ERG used for activity of an eye is an abbreviation of
----------------------
Unit of voltage (v) is equivalent to unit
----------------------
Shark's organ for detection of electric field is named as
----------------------
Transformer is being used in
----------------------
Emf produced in conductor is known as
----------------------
A metallic ring is attached to wall of a room. when north pole of magnet is brought near ring, induced current in ring is
----------------------
A helium nucleus enters perpendicularly in magnetic field 'b' with velocity 'v', then magnetic force acting on it will be
----------------------
Lenz's law is in accordance with law of conservation of
----------------------
Value of 1 ev is equivalent to value of
----------------------
If charged particle of 2e falls at potential difference of 6 v, then energy required to fall will be
----------------------
In a transistor, emitter current is
----------------------
A simple diode can be used as
----------------------
Current flowing into base of transistor is 100 µa and current gain is 100 µa, its collector current will be
----------------------
Least doped region in a transistor is
----------------------
Device named as a transistor has
----------------------
At position of (4i + 3j) by a point charge 5x10⁻⁶ c placed at origin will produce electric field of
----------------------
Two point charges -1x10⁻⁶ c and 4x10⁻⁶ c separated by 3 m distance have zero field location of
----------------------
Product of resistance of 1 Ω and capacitance of 1 farad is equal to
----------------------
According to equation of continuity, when water falls its speed increases, while its cross sectional area
----------------------
Simplified equation of continuity is represented as
----------------------
If fluid is incompressible and is steady, its mass is
----------------------
Constant of equation of continuity is known as
----------------------
Density of water is equal to
----------------------
Errors that occur during measurement of quantities are of
----------------------
Prefix named as femto has a factor of
----------------------
Systematic error occurred due to poor calibration of instrument that can be corrected by
----------------------
Error that occurs due to equally affected measurements is called
----------------------
Error that occurs during measurement of quantities is
----------------------
If layers of fluid have frictional force between them, then it is known as
----------------------
If every particle of fluid has irregular flow, then flow is said to be
----------------------
If every particle of fluid follows same path, then flow is said to be
----------------------
A racing car has a body with
----------------------
Force due to water flow is represented by formula
----------------------
For gauss's law, point charges in closed surface must be distributed
----------------------
Gauss's law due to different charge distribution is used to calculate
----------------------
Law stated as flux is 1/Eo times total charge is
----------------------
A geo-stationary satellite orbiting around earth is used for
----------------------
Orbital motion of geo-stationary satellite with respect to motion of earth is
----------------------
Artificial satellites are objects that orbit around earth due to
----------------------
Geo-stationary satellites are also known as the
----------------------
A geo-stationary satellite orbits around earth once
----------------------
Self-induced emf is sometimes also known as
----------------------
Changing current in one coil induces emf in another, this phenomena is known as
----------------------
Negative sign of equation of self-induction shows that
----------------------
Changing current in a coil produces emf in same coil. this phenomenon is known as
----------------------
Units given by system international for measuring physical quantities are called
----------------------
According to system international, amount of substance is measured in
----------------------
Base units of physical quantities given by system international are
----------------------
System international for describing units was built up from
----------------------
According to system international, length of substance is measured in
----------------------
Main frontiers of fundamental science are
----------------------
Branch of science that deals with natural phenomena is called
----------------------
This whole world is composed of small particles that are made up of
----------------------
Branch of science dealing with matter and energy and their relationship is called
----------------------
Branch of physics that deals with study and properties of solids is called
----------------------
Law of conservation of angular momentum is mostly used in
----------------------
"if no external torque is applied on a body, total angular momentum remains constant" stated law is called
----------------------
Point of intersection of two coordinate axes is called
----------------------
Position vector is vector that defines vector's
----------------------
Vector quantities having directions are denoted by
----------------------
Decomposing vectors into mutually perpendicular components is called
----------------------
Product of mass and velocity is known as
----------------------
Time rate of change of momentum of a body is equal to
----------------------
Throwing a package onto shore from a boat at rest will cause boat to move
----------------------
Product of force and time is known as
----------------------
Our hair on our skull act like a
----------------------
In defining orbital velocity of satellite, thing which is unimportant is
----------------------
First human satellite of earth was man named as
----------------------
Ideal standard for measuring base quantities involves characteristics that are
----------------------
A physical quantity is
----------------------
Base quantities can be measured according to the
----------------------
One of physical quantities which is not a derived quantity
----------------------
Ideal standard for measuring base quantities mainly involves
----------------------
Researches of studying nature and type of forces that hold things together are dealt by
----------------------
Branch of physics that deals with properties and behavior of elementary particles is called
----------------------
Computer which is a product of chips has been developed from basic idea of
----------------------
"physics is branch of science" name physics means
----------------------
Branch of physics that deals with nuclear energies is called
----------------------
F = ma, this equation is referred to as newton's
----------------------
If a body has 200 kg mass and its velocity gets reduced from 25 m s⁻¹ to 20 m s⁻¹ in 4 seconds, average retarding force on a body will be
----------------------
If a body moving with initial, constant velocity of 10 m s⁻¹, accelerates for 2 seconds at a constant rate of 12 m s-2, final velocity of body will be
----------------------
Average angular velocity of a body rotating at angle of 30° for 5 seconds will be
----------------------
If body accelerates from rest to angular velocity of 45 revolutions/min in a time of 1.6 seconds, its angular acceleration will be
----------------------
Power of machine when work done is 30 j in a time interval 5 seconds will be
----------------------
Body having weight 50 kg turning in a circle at 5 m s⁻¹, if radius of circle is 5 m, force exerted on body to hold it in circular path is
----------------------
A car of 200 kg is moving in a circle of radius 4.3 m with angular velocity of 2 rad s⁻¹, it's angular momentum will be
----------------------
If motor gets over loaded, then its
----------------------
With alternative current, inductor behaves like
----------------------
A metal rod of 25 cm is moving at 0.5 m s⁻¹ in direction perpendicular to 0.25 t magnetic field, emf produced is
----------------------
Law that states that direction of induced current is always as to oppose change which causes current, is
----------------------
While grasping wire in right hand with thumb pointing to direction of current is known as
----------------------
A man of mass 30 kilograms climbs stairs of height 5 meters in 4 seconds. power output produced will be
----------------------
If a brick having mass 2 kg is dropped from height of 5 m, its velocity at a height of 3 m will be
----------------------
10 bricks each having mass of 1.5 kg with thickness of 6 cm will have work done to stack bricks
----------------------
2 kg ball moving with velocity of 5 m s⁻¹ collides with 4 kg ball at rest. velocities of both balls after collision will be
----------------------
A ball is thrown from height of 10m with velocity 21 m s⁻¹, it will hit ground at
----------------------
Electro motive force induced by motion of conductor across magnetic field is called
----------------------
Magnetic field is 0.6t and rate of change of area is 0.8 m²/s when n=1, induced emf would be
----------------------
SI unit of magnetic induction is
----------------------
Magnetic field is set up in region surrounding current carrying
----------------------
If a current carrying conductor is placed in uniform magnetic field parallel to direction of field then force experienced by conductor will be
----------------------
Vector product of two vectors is also known as
----------------------
Multiplication of two vectors is of
----------------------
Cross product of axb with sin(0) would produce results equal to
----------------------
Scalar product of a.b with angle 180° would produce results equal to
----------------------
Height of projectile is given by formula
----------------------
Time of flight of body is given by formula
----------------------
A typical rocket consumes fuel on amount of
----------------------
Typical rocket ejects burnt gases at speeds of over
----------------------
As body rolls down, its gravitational energy changes to
----------------------
Rotational kinetic energy of disc is given by
----------------------
Rotational kinetic energy of hoop is
----------------------
Wheel will have both rotational and translational kinetic energies when it
----------------------
According to si units, mass of a substance is measured in
----------------------
Derived units of physical quantities given by si are
----------------------
Ampere unit according to si units is a
----------------------
Angle between two radii of circle that cut off on circumference is called
----------------------
"candela", according to system international is a
----------------------
Zero digit between two significant figures is
----------------------
In figure '12.7', first two digits are accurate while third one is
----------------------
Number of digits that are reasonably sure are called
----------------------
After decimal point, number is less than 5 which is to be neglected,then retained number
----------------------
Accurately known digits and first doubtful digit are called
----------------------
Two forces 10 n and 20 n making an angle 30° and 60° will give a resultant force of
----------------------
Dimensions of coefficient of viscosity is
----------------------
Unit vector in direction of vector f = 6i + 5j is
----------------------
Net force acting on a droplet of water is equal to
----------------------
When net force acting on a droplet becomes zero, its constant speed is known as
----------------------
When net force acting on a droplet becomes zero, it falls with
----------------------
Dimensions of rate of change of flux are equivalent to those of
----------------------
Turn ratio (r) for a step-up transformer is
----------------------
Practical application of mutual induction is
----------------------
Transformer is device that works on principle of
----------------------
Efficiency of transformer is defined as
----------------------
A transistor can be used as a switch on if vce is nearly
----------------------
Base of transistor has a thickness of
----------------------
Photo diodes' applications include the
----------------------
Prefix naming as centi has a factor of
----------------------
Zero error produced by measuring instruments is called
----------------------
Prefix known as mega has a symbol
----------------------
Repeated measurement having different values are the
----------------------
Uncertainty of measurement can occur due to the
----------------------
At surface of earth where air friction is negligible, objects fall with the
----------------------
From equations of distance, correct one is
----------------------
Correct equation of distance is
----------------------
Velocity of vertically thrown ball with time will be
----------------------
Direction of resultant of two vectors is given by
----------------------
Vector's x-components are represented by formula of
----------------------
Y-components of vectors are represented by formula of
----------------------
X-components of vectors are represented by the
----------------------
Resultant magnitude of two vectors is given by formula
----------------------
Product of velocity and mass is called
----------------------
In a plane, direction of vectors is denoted by

                                             questions  checker
0    Device that converts electrical energy into me...     True
1    Alternative current generator is basically bas...     True
2    In alternative current generator, ac current r...     True
3    "a current carrying coil placed in magnetic fi...     True
4    At a particular instant, acceleration of a bod...     True
..                                                 ...      ...
262          When angle is equal to zero, work will be     True
263  When an object is moved in gravitational field...     True
264  System international unit of work done is newt...     True
265  If angle of work done is less than 90°, then w...     True
266      Product of force and displacement is known as     True

[267 rows x 2 columns]

In [108]:

first_cleaner = ['{', '[', '(','$', '#', '<', '-', '+', '±', '∠', '|', 'π','~', '∆' ,'∑', '∏', 'e', 'μ', 'σ', 'n', 'ε', '∞', '' ]
last_cleaner = ['=','}', ']', ')', '°', '|', 'π', '!', '∆', 'γ', 'μ', 'ε', '∞']
greek_alphabets = ['Α', 'α', 'Β', 'β', 'Γ', 'γ', 'Δ', 'δ', 'Ε', 'ε', 'Ζ', 'ζ', 'Η', 'η', 'Θ', 'θ', 'Ι', 'ι', 'Κ', 'κ', 'Λ', 'λ', 'Μ', 'μ', 'Ν', 'ν','Ξ', 'ξ', 'Ο', 'ο', 'Π', 'π', 'Ρ', 'ρ', 'Σ', 'σ', 'ς', 'Τ', 'τ', 'Υ', 'υ', 'Φ', 'φ', 'Χ', 'χ', 'Ψ', 'ψ','Ω','ω', '∆' ,'∑', '∏', 'e', 'μ', 'σ', 'n', 'ε', '∞']
wh_list = ['what', 'who', 'whom', 'whose','how', 'where', 'when','why','which']

def cleaner(question):
    
    # part one--cleaner
    count = 0
    while ((not question[0].isalnum()) and (question[0] not in first_cleaner) and (question[0] not in greek_alphabets)) or ((not question[-1].isalnum()) and (question[-1] not in last_cleaner) and (question[-1] not in greek_alphabets)):
        if (not question[0].isalnum()) and (question[0] not in first_cleaner) and (question[0] not in greek_alphabets):
            question = question.replace(question[0],'', 1)
        if (not question[-1].isalnum()) and (question[-1] not in last_cleaner) and (question[-1] not in greek_alphabets):
            if question[::-1][0] == '.':
                count += 1
            question = question[::-1].replace(question[::-1][0], '', 1)[::-1]
    if count >=3:
        add_dot = True
    else:
        add_dot = False
        
    # part two--add punctutation
    unnecessary_in_wh = ['=', '?']
    question_list = question.lower().split(' ')
    question_filt = [True for q in question_list if q in wh_list]
    question_joined = ' '.join(question_list)
    if any(question_filt):
        while question_joined[-1] in unnecessary_in_wh:
            question_joined = question_joined[::-1].replace(question_joined[::-1][0], '', 1)[::-1]
        question_joined = (question_joined).rstrip() + '?'
    else:
        # this while field should be customized later based on other inputs
        while question_joined[-1] == '=':
            question_joined = question_joined[::-1].replace(question_joined[::-1][0], '', 1)[::-1]
        if '...' in question_joined and not add_dot:
            question_joined = question_joined + '.'
        else:
            question_joined = question_joined + '.....'
    return question_joined.capitalize()

In [113]:
cleaner('hello there ...  are you..&     #$$    ##    ')

'Hello there ...  are you.'

In [115]:
pwd

'/home/bishal/Playground'

In [125]:
df.to_csv('hell.csv', index=False)

In [126]:
pd.read_csv('hell.csv')

,Unnamed: 0,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,0,1,Device that converts electrical energy into me...,Ac generator,Dc generator,Cell,Dc motor,D
1,1,2,Alternative current generator is basically bas...,Amperes law,Lenz's law,Faradays law,Coulombs law,C
2,2,3,"In alternative current generator, ac current r...",20 times per second,50 times per second,Once per second,Twice per second,B
3,3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,Dc motor,Ac generator,Both a and b,B
4,4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Instantaneous velocity,Instantaneous displacement,Instantaneous speed,A
...,...,...,...,...,...,...,...,...
262,262,263,"When angle is equal to zero, work will be",Positive,Negative,Zero,Maximum,D
263,263,264,When an object is moved in gravitational field...,Work done by a constant force,Work done by a variable force,Work done by a gravitational field,Both a and b,C
264,264,265,System international unit of work done is newt...,Joule,Kelvin,Ampere,Candela,A
265,265,266,"If angle of work done is less than 90°, then w...",Negative,Positive,Zero,Both a and b,A
266,266,267,Product of force and displacement is known as,Distance,Speed,Work done,Force,C

In [122]:
pd.read_csv('hell.csv')

,Unnamed: 0,Unnamed: 0.1,S.N.,Question,Option A,Option B,Option C,Option D,Correct Option
0,0,0,1,Device that converts electrical energy into me...,Ac generator,Dc generator,Cell,Dc motor,D
1,1,1,2,Alternative current generator is basically bas...,Amperes law,Lenz's law,Faradays law,Coulombs law,C
2,2,2,3,"In alternative current generator, ac current r...",20 times per second,50 times per second,Once per second,Twice per second,B
3,3,3,4,"""a current carrying coil placed in magnetic fi...",Dc generator,Dc motor,Ac generator,Both a and b,B
4,4,4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Instantaneous velocity,Instantaneous displacement,Instantaneous speed,A
...,...,...,...,...,...,...,...,...,...
262,262,262,263,"When angle is equal to zero, work will be",Positive,Negative,Zero,Maximum,D
263,263,263,264,When an object is moved in gravitational field...,Work done by a constant force,Work done by a variable force,Work done by a gravitational field,Both a and b,C
264,264,264,265,System international unit of work done is newt...,Joule,Kelvin,Ampere,Candela,A
265,265,265,266,"If angle of work done is less than 90°, then w...",Negative,Positive,Zero,Both a and b,A
266,266,266,267,Product of force and displacement is known as,Distance,Speed,Work done,Force,C

In [124]:
pd.read_csv('~/Desktop/newdir/capitalize/cleaned_csv_class11datacollection.csv')

,Unnamed: 0,S.N.,QUESTION,OPTION A,OPTION B,OPTION C,OPTION D,CORRECT ANSWER
0,0,1,Device that converts electrical energy into me...,Ac generator,Dc generator,Cell,Dc motor,D
1,1,2,Alternative current generator is basically bas...,Amperes law,Lenz's law,Faradays law,Coulombs law,C
2,2,3,"In alternative current generator, ac current r...",20 times per second,50 times per second,Once per second,Twice per second,B
3,3,4,A current carrying coil placed in magnetic fie...,Dc generator,Dc motor,Ac generator,Both a and b,B
4,4,5,"At a particular instant, acceleration of a bod...",Instantaneous acceleration,Instantaneous velocity,Instantaneous displacement,Instantaneous speed,A
...,...,...,...,...,...,...,...,...
262,262,263,"When angle is equal to zero, work will be?",Positive,Negative,Zero,Maximum,D
263,263,264,When an object is moved in gravitational field...,Work done by a constant force,Work done by a variable force,Work done by a gravitational field,Both a and b,C
264,264,265,System international unit of work done is newt...,Joule,Kelvin,Ampere,Candela,A
265,265,266,"If angle of work done is less than 90°, then w...",Negative,Positive,Zero,Both a and b,A
266,266,267,Product of force and displacement is known as....,Distance,Speed,Work done,Force,C

In [127]:
pd.read_csv('/home/bishal/Desktop/newdir/capitalize/randomize_cleaned_class11datacollection.csv')

,S.N.,QUESTION,OPTION A,OPTION B,OPTION C,OPTION D,CORRECT ANSWER
0,1,Scalar product of a.b with angle 180° would pr...,Ab,(-ab),A.b,B,C
1,2,Electric force between two charges is similar ...,Two point masses,Two point charges,Two bodies,Two distances,B
2,3,1 µf of capacitance is equal to.....,10⁻² f,10⁻³ f,10⁻⁴ f,10⁻⁶ f,A
3,4,Device named as a transistor has.....,Emitter heavily doped,Emitter and collector equally doped,Collector heavily doped,Both a and b,B
4,5,Space in which gravitational force acts on a b...,Force,Speed,Work done,Gravitational field,D
...,...,...,...,...,...,...,...
262,263,Capacitor is used to store electric.....,Charge,Energy,Voltage,Both a and b,A
263,264,Time rate of change of displacement is known a...,Velocity,Distance,Speed,Displacement,D
264,265,Vector sum of two vectors is also called.....,Magnitude,Resultant,Velocity,Direction,D
265,266,Position vector that defines position of vecto...,(a² + b² + c²),√(a + b + c),√(a²-b² + c²),√(a² + b² + c²),D
266,267,Power of machine when work done is 30 j in a t...,145 w,125 w,120 w,150 w,C