In [1]:
import pandas as pd
import pandas_gbq
from google.cloud import bigquery
%load_ext google.cloud.bigquery
# Set your default project here
pandas_gbq.context.project = 'bigquery-public-data'
pandas_gbq.context.dialect = 'standard'

In [3]:
%%bigquery

select 5*5

DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

In [5]:
ls

README.md             images/               learn bigquery.ipynb
flask-videstreamer/   ipynb-files/          learn_graphql/
htmcore/              js/                   oldprojects/

In [9]:
ls

README.md                       js/
flask-videstreamer/             learn bigquery.ipynb
htmcore/                        learn-347411-7cae9f54081a.json
images/                         learn_graphql/
ipynb-files/                    oldprojects/

In [10]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="learn-347411-7cae9f54081a.json"

In [11]:
%%bigquery

select 5*5

Query complete after 0.10s: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 270.79query/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.58s/rows]

   f0_
0   25

In [14]:
%%bigquery
with person as (select 'bishal' as name, 13 as luckynum union all
               select 'manish', 6 union all
               select 'hemant', 0)
select * from person

Query complete after 0.00s: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 274.12query/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.96rows/s]

     name  luckynum
0  bishal        13
1  manish         6
2  hemant         0

### Bigquery chapter 3 by oreily

-- With students as (select 'bishal' as name, 26 as age, 1996 as dob UNIon all
-- select 'manish', 27, 1995 union all
-- select 'hemant', 28, 1994 union all
-- select 'kizito', 25, 1997),
-- teachers as (select 'ddobric', 45 as age, 'cloud computing' as subject union all
-- select 'Falkenberg', 61, 'Vector Analysis' union all
-- select 'Bestfort Shala', 46, 'It security' union all
-- select 'Verginia Sanchez', 55, 'Deutche Language course')

-- select dob + age as present_year from students;
-- select substring(name, 1, 3) as substri from students
-- select max(age) from students
-- select round(avg(students.age)), round(avg(teachers.age)), round(5.5), round(5.4), round(5.6), round(5.9) from students, teachers
-- select 10/5
-- select 10/0 -- results in division by zero error
-- to solve this issue a better way to divide is to use IEEE_Divide
-- select IEEE_Divide(10.9, 0.0) -- return Infinity as output
-- select safe_divide(10, 0) -- return null
-- select log(10)
-- select log(0) -- gives floating point error in function
-- select log(-1) -- gives floating point error in function

-- You can make any scalar function return instead of raising an error by prefixing it with safe. this makes function return null instead of throwing error
-- select safe.log(-1) -- returns null instead of throwing error
-- SAFE function method is restricted to scalar function
-- safe method doesnot work on aggregate or analytics or user-defined function-- only works on scalar function

--  Null followed by NaN is assumed to be smaller than valid numbers (including -infinity) for the purposes of ordering

-- WHEN NULL IS COMPARED TO ANYTHING, THE RESULT IS NULL. SO NULL IS CHECKED USING IS NULL OR IS NOT NULL. 


-- != and <> bot means NOT EQUAL TO.
-- select 10 = 10, 10 != 10, 10 <> 10
-- USING NUMERIC DATA TYPE INSTEAD OF INT64 AND FLOAT64 CAN BE MORE PRECISE AS IT IS REPRESENTED AS 38 DIGITS NUMBER
-- WITH 9 OF THEM TO REPRESENT THE DIGIT AFTER DECIMALS, IRRESPECTIVE OF BITS(0, 1) AS OF IN INT64 AND FLOAT64

-- select 22/7 --  3.1428571428571428

-- select numeric '3.14285728'
-- select 3.1428571428571428

-- Boolean expressions  include ,AND ,OR , NOT, as well as parentheses to control the order of execution.
-- we can use comparision operator with boolean variables

-- To compare with the built-in constants, we can use IS
-- select true is not true

-- THE COMPARISION OPERATOR RETURNS NULL FOR COMPARISION AGAINST NULL BUT THE IS OPERATOR DOESNOT RETURNS NULL

-- *** CONDITIONAL EXPRESSION *** ---
-- with sales as (select 36 as unit_price, 45 as units, 10 as discount union all
-- select 45 as unit_price, 40 as units, null as discount union all
-- select null as unit_price, null as discount, 60 as units )

-- select * from sales

-- we can use if clause to specify the default value

-- select *, (unit_price*units) - discount as sales_price from sales
-- select *, ((if(unit_price is null, 10, unit_price) * if(units is null, 0, units)) - if (discount is null or discount > 15, 15, discount )) as sales_price from sales

-- as in above, we can handle null using if clause
-- better way to handle null is by using coalesce(expressions,.....)
-- coalesce(a, b, c, d, e, 8, null)-- in this example
---- if a is null, b is output
---- if b is null, c is output
---- if c is null, d is output
---- if d is null, e is output
---- if e is null, 8 is output
---- so only goes to 8 as it is not null
---- if only null is seen, then null is output

-- coalesce calculates only till non-null, if null then skips to next, if final is null, then null is outputted
-- ifnull(a, b) is same as if(a is null, b, a) -- it means - if a is null then b else a
-- select *, coalesce( (unit_price) * units - discount, (unit_price) * units , 00, null ) as sales_price from sales
-- select *, ifnull( (unit_price) * units - discount, (unit_price) * units ) as sales_price from sales

-- CASTING AND COERCION

-- with employe as (select 'bishal' as name, '20' as working_hour union all
-- select 'ishank', '40' union all
-- select 'newperson', 'not_available')

-- select * from employe

-- select cast ('10' as INT64)
-- select cast('true' as bool)
-- select cast(10 as string)
-- select cast(10 as int64)

-- select cast('my name' as int64) -- Cound not cast error 

-- To use safe casting use safe_cast()

-- select safe_cast('my name' as int64)

-- IF EXPRESSION IS INVALID, SAFE_CAST RETURN NULL, WHICH IS NOT USED BY SCALAR OPERATIONS

-- select sum(safe_cast(working_hour as int64)) from employe -- works as we use safe_case

-- Implicit conversion is called COERCION
-- IN , INT64, FLOAT64, NUMBERS BIG QUERY DOES IMPLICIT CONVERSION AS REQUIRED --  COERCION

-- SELECT CAST(0 AS BOOL) RETURN false, but '0' cannot be converted to boolean

--with categorize as (
--  select 'a' as letter, true as is_vowel union all
--    select 'b', false union all
--    select 'c', false union all
--    select 'd', false union all
--    select 'e', true
--)

-- select * from categorize

-- select sum(if(is_vowel, 1, 0)) from categorize -- returns 2

-- better approach to find the count of true items is using COUNTIF

-- select countif(is_vowel) from categorize -- same as above statement but a better approach -- return 2

-- with places as  (select * from unnest(['frankfurt', 'wiesbaden', 'offenbach', 'rüsselsheim']) as city)

-- select city, lower(city) as lower, length(city) as len, strpos(city, 'e') from places  -- if no strpos string is match -- returns 0

-- with users as (select 'bisal@gmail.com' as email, 'nepal' as country union all
-- select 'max@hotmail.com', 'germany' union all
-- select 'chair@for.com', 'forest')
-- using concat of string to give user introduction
-- select concat(substr(email, 1, strpos(email, '@')-1), " is from ", country) as intro from users


-- PRINTING AND PARSING
-- select format('hi my name is %s', 'bishal') -- results -- hi my name is bishal

-- select ends_with('bishal', 'al') -- returns true

-- select starts_with(value1, value2)
--string manipulation function
--LPAD -- RPAD -- TRIM -- LTRIM --RTRIM -- REVERSE

-- select regexp_extract_all("hi my 3434 is bishal 355343. I live in chitwan", r'\d{3}') -- page 97 of book
-- \d{5} represent 5 decimal digit
-- (?:[-\s])? represent optional hypen by (-) or space (' ') by \s


-- REGULAR EXPRESSION
-- select regexp_contains(cast(number as string), r'\d[3-9]'), cast(number as string) from (select * from unnest([1111, 3333, 5444, 12333, 43434, 44444,44444]) as number)
-- regexp_select, regexp_select_all, regex_contains

--  TIMESTAMPS, DATE, DATETIME

-- select current_timestamp(), current_time()

-- select parse_date("%Y%m%d", '20110923')

-- use TIME_STAMP TO REPRESENT UTC TIME


-- select extract(year from current_timestamp())
-- use extract to extract year, month or day or week or time from the datetime

-- ARITHMETICS WITH TIMESTAMP
-- select timestamp_add(current_timestamp() , interval 1 DAY)
-- select timestamp_sub(current_timestamp() , interval 1 HOUR)

-- select timestamp_diff(current_timestamp() , timestamp_add(current_timestamp(), interval 11 DAY), DAY)

In [16]:
%%bigquery
select * from `bigquery-public-data`.covid19_nyt.us_states limit 5

Query complete after 0.00s: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 272.78query/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.11rows/s]

         date state_name state_fips_code  confirmed_cases  deaths
0  2020-03-15       Guam              66                3       0
1  2020-03-16       Guam              66                3       0
2  2020-03-17       Guam              66                3       0
3  2020-03-18       Guam              66                8       0
4  2020-03-19       Guam              66               12       0

In [18]:
%%bigquery
select * from `bigquery-public-data`.covid19_nyt.us_states order by deaths desc limit 5

Query complete after 0.00s: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 327.22query/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:01<00:00,  3.52rows/s]

         date  state_name state_fips_code  confirmed_cases  deaths
0  2022-04-15  California              06          9158440   89744
1  2022-04-14  California              06          9151205   89629
2  2022-04-13  California              06          9136777   89554
3  2022-04-12  California              06          9135719   89514
4  2022-04-11  California              06          9134794   89484

In [1]:
%%bigquery
select 5+4

UsageError: Cell magic `%%bigquery` not found.

In [2]:
%load_ext google.cloud.bigquery

In [3]:
%%bigquery
select 5+4

DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

In [4]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="learn-347411-7cae9f54081a.json"

In [6]:
%%bigquery
select 5+4

Query complete after 0.03s: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 216.50query/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.48s/rows]

   f0_
0    9

In [8]:
%%bigquery
select 5+4 as sum

Query complete after 0.01s: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 220.27query/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.43s/rows]

   sum
0    9