In [2]:
import seaborn as sns

In [4]:
import pandas as pd


df = pd.read_csv('datas/melb_data.csv')

In [5]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [10]:

df = pd.read_csv('datas/melb_data.csv', usecols=[ 'Price', 'Rooms', 'Distance', 'Date'])

In [11]:
df

       Rooms      Price        Date  Distance
0          2  1480000.0   3/12/2016       2.5
1          2  1035000.0   4/02/2016       2.5
2          3  1465000.0   4/03/2017       2.5
3          3   850000.0   4/03/2017       2.5
4          4  1600000.0   4/06/2016       2.5
...      ...        ...         ...       ...
13575      4  1245000.0  26/08/2017      16.7
13576      3  1031000.0  26/08/2017       6.8
13577      3  1170000.0  26/08/2017       6.8
13578      4  2500000.0  26/08/2017       6.8
13579      4  1285000.0  26/08/2017       6.3

[13580 rows x 4 columns]

only one features-- univariate analysis

two features -- bivariate analysis

Types of plot:
    Distplot
    JoinPlot
    pairplot

In [13]:
df.head()

   Rooms      Price       Date  Distance
0      2  1480000.0  3/12/2016       2.5
1      2  1035000.0  4/02/2016       2.5
2      3  1465000.0  4/03/2017       2.5
3      3   850000.0  4/03/2017       2.5
4      4  1600000.0  4/06/2016       2.5

In [18]:
df.to_csv('room_data.csv')