In [1]:
ls ..

1_42132_p_adc.npy      env/                   learn_graphql/
BigQuery/              experiments_one. 1703/ learn_redpitaya/
CNN/                   flask-videstreamer/    oldprojects/
README.md              ipynb-files/
docker_containers/     js/

In [2]:
cd ..

/Users/bisalgt/Projects/playground

In [3]:
ls

1_42132_p_adc.npy      env/                   learn_graphql/
BigQuery/              experiments_one. 1703/ learn_redpitaya/
CNN/                   flask-videstreamer/    oldprojects/
README.md              ipynb-files/
docker_containers/     js/

In [4]:
import numpy as np

data = np.load("experiments_one. 1703/binaries/1_56354_p_fft.npy")

In [5]:
data

array(b'\x00\x00\x80B\x00\x00*C\x00\x00\x80?\x00\x00\x00@(k\xeeB\x00\x00\x00\x00(k\xeeI\x00\x00@A\x00\x00\x00\x00\x00\x00\xe0E\xb1\xfa\x0f@\x00\x00\x00\x00\x00\x00\x00\x00\xaeGa>\x00\x00\x00\x00\x00\x00\x00\x00*\x003\x00$\x001\x005\x00(\x00,\x009\x00=\x00+\x00%\x00;\x00%\x00-\x00\x1a\x00\'\x00\x11\x00"\x000\x00\x13\x00a\x00(\x00q\x00\x16\x00\x9b\x005\x00\xa2\x00\x19\x00\xc2\x00F\x00\xc7\x00V\x00\x07\x01\xc7\x00&\x01\xd5\x00\x9f\x00\xc8\x00i\x01\xa3\x01\xf5\x00S\x01J\x01\xcb\x01\xd7\x00\xd3\x01\r\x02\xd4\x021\x01\x96\x00\xdb\x01\xc3\x03\xf8\x02\x9e\x02\x86\x01\xa6\x02\x10\x03\xe2\x03\xe8\x03\xe3\x02Z\x02\xf9\x00\x90\x01\x7f\x01\x13\x02B\x01z\x01\xce\x00\xec\x00a\x00\xe1\x00w\x00\x7f\x00*\x00z\x00(\x00]\x00G\x00p\x003\x00b\x00\\\x00W\x00:\x00W',
      dtype='|S234')

In [35]:
data_bytes = data.tobytes()

In [36]:
import struct

header_data = []
for i in struct.iter_unpack('@f', data_bytes[:64]):
    header_data.append(i[0])

ultrasonic_data = []
for i in struct.iter_unpack('@h',data_bytes[64:]):
    ultrasonic_data.0append(i[0])
    
print(header_data)
print(ultraso0nic_data)

print(len(header_data) + len(ultrasonic_data))

[64.0, 170.0, 1.0, 2.0, 119.20928955078125, 0.0, 1953125.0, 12.0, 0.0, 7168.0, 2.249675989151001, 0.0, 0.0, 0.2199999988079071, 0.0, 0.0]
[42, 51, 36, 49, 53, 40, 44, 57, 61, 43, 37, 59, 37, 45, 26, 39, 17, 34, 48, 19, 97, 40, 113, 22, 155, 53, 162, 25, 194, 70, 199, 86, 263, 199, 294, 213, 159, 200, 361, 419, 245, 339, 330, 459, 215, 467, 525, 724, 305, 150, 475, 963, 760, 670, 390, 678, 784, 994, 1000, 739, 602, 249, 400, 383, 531, 322, 378, 206, 236, 97, 225, 119, 127, 42, 122, 40, 93, 71, 112, 51, 98, 92, 87, 58, 87]
101

In [46]:
import os, glob
path = 'experiments_one. 1703/binaries/'
for filename in glob.glob(os.path.join(path, '*.npy')):
    with open(os.path.join(os.getcwd(), filename), 'r') as f: # open in readonly mode
        print(dir(f))
        print(f.name)
        data = np.load(f.name)
        data_bytes = data.tobytes()
        header_data = []
        for i in struct.iter_unpack('@f', data_bytes[:64]):
            header_data.append(i[0])

        ultrasonic_data = []
        for i in struct.iter_unpack('@h',data_bytes[64:]):
            ultrasonic_data.append(i[0])

        print(header_data)
        print(ultrasonic_data)

        break

['_CHUNK_SIZE', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__ne__', '__new__', '__next__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_checkClosed', '_checkReadable', '_checkSeekable', '_checkWritable', '_finalizing', 'buffer', 'close', 'closed', 'detach', 'encoding', 'errors', 'fileno', 'flush', 'isatty', 'line_buffering', 'mode', 'name', 'newlines', 'read', 'readable', 'readline', 'readlines', 'reconfigure', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'write_through', 'writelines']
/Users/bisalgt/Projects/playground/experiments_one. 1703/binaries/1014_56688_p_fft.npy
[64.0, 170.0, 1.0, 2.0, 119.20928955078125, 0.0, 1953125.0, 12.0, 0.0, 3009.0, 1.5359916687011719, 0.0, 0.0, 0.2199999988079071, 0.0, 0.0]
[18, 59, 34, 44, 56, 28, 69, 29, 77, 21, 84, 44, 82, 47, 75, 65, 56, 86, 58, 105, 31, 125, 28, 145, 28, 170, 14, 176, 68, 241, 80, 231, 158, 300, 178, 322, 416, 529, 538, 409, 502, 384, 484, 207, 336, 377, 673, 670, 959, 703, 485, 219, 534, 519, 531, 538, 679, 877, 999, 995, 751, 744, 421, 392, 247, 381, 273, 346, 273, 282, 217, 159, 153, 141, 142, 91, 97, 82, 101, 82, 92, 57, 78, 66, 79]

In [38]:
ls

1_42132_p_adc.npy      env/                   learn_graphql/
BigQuery/              experiments_one. 1703/ learn_redpitaya/
CNN/                   flask-videstreamer/    oldprojects/
README.md              ipynb-files/
docker_containers/     js/

In [47]:
import pandas as pd

In [60]:
df = pd.DataFrame([ultrasonic_data])

In [61]:
df

,0,1,2,3,4,5,6,7,8,9,...,75,76,77,78,79,80,81,82,83,84
0,18,59,34,44,56,28,69,29,77,21,...,91,97,82,101,82,92,57,78,66,79

In [62]:
df.insert(0, "label", ["person",])

In [63]:
df

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [64]:
df2 = df.copy()

In [65]:
df2.append(df)

/var/folders/_w/n_8gf6lx5hg6605yqrhm6cnh0000gn/T/ipykernel_1237/2531980288.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2.append(df)

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [72]:
df3 = pd.concat([df2, df])

In [73]:
df2

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [74]:
df

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [75]:
df3

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [76]:
df4 = pd.concat([df3, df])

In [77]:
df4

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [87]:
df4.to_csv("df.csv", index=False, header=False)

In [90]:
df5 = pd.read_csv("df.csv", header=None)

In [91]:
df5

,0,1,2,3,4,5,6,7,8,9,...,76,77,78,79,80,81,82,83,84,85
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
1,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
2,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [86]:
df5.iloc[1, 0:5]

label    person
0            18
1            59
2            34
3            44
Name: 1, dtype: object

In [93]:
file_name = "/Users/bisalgt/Projects/playground/experiments_one. 1703/binaries/1014_56688_p_fft.npy"
file_name.split("/")[-1].split("_")[2]

'p'

In [94]:
df = pd.DataFrame()

In [95]:
df3

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [97]:
df = pd.concat([df, df3])

In [98]:
df = pd.concat([df, df3])

In [100]:
df.iloc[0,0] = "find me"

In [101]:
df

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,find me,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [103]:
pd.concat([df3, df])

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,find me,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [140]:
import os, glob
path = 'experiments_one. 1703/binaries/'
final_df = pd.DataFrame()
for filename in glob.glob(os.path.join(path, '*.npy')):
    with open(os.path.join(os.getcwd(), filename), 'r') as f: # open in readonly mode
        data = np.load(f.name)
        data_bytes = data.tobytes()
        header_data = []
        for i in struct.iter_unpack('@f', data_bytes[:64]):
            header_data.append(i[0])

        ultrasonic_data = []
        for i in struct.iter_unpack('@h',data_bytes[64:]):
            ultrasonic_data.append(i[0])
        
        tmp_df = pd.DataFrame([ultrasonic_data])
        
        label_output = f.name.split("/")[-1].split("_")[2]
        
        if label_output.lower() == "p":
            label_output = "person"
        else:
            label_output = "non_person"
        
        tmp_df.insert(0, "label", [label_output,])
        
        final_df = pd.concat([final_df, tmp_df])
        
final_df.to_csv("final_df.csv", index=False)

In [141]:
read_data = pd.read_csv("final_df.csv")

In [142]:
read_data

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
1,person,59,54,55,56,45,63,52,67,45,...,163,96,121,99,121,96,116,82,96,84
2,person,43,8,26,30,19,15,35,36,20,...,48,55,62,32,55,44,35,41,57,39
3,non_person,92,77,91,96,74,91,81,106,62,...,82,199,153,171,125,179,140,127,119,142
4,person,212,130,51,19,69,87,147,163,173,...,269,230,184,180,155,137,105,108,77,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6771,person,69,74,76,66,70,69,78,58,93,...,132,170,196,154,134,162,140,123,113,136
6772,person,44,24,46,38,21,52,38,65,30,...,144,64,94,74,96,52,88,71,72,56
6773,person,11,20,3,4,7,13,16,9,13,...,19,44,36,27,7,23,28,16,9,17
6774,person,83,58,92,78,61,89,74,83,63,...,105,187,148,164,117,191,139,130,114,163
6775,non_person,32,49,39,53,53,36,61,47,69,...,91,97,126,76,94,83,101,74,79,73

In [110]:
read_data.iloc[:, 0]=="non_person"

0       False
1       False
2       False
3        True
4       False
        ...
6771    False
6772    False
6773    False
6774    False
6775     True
Name: 0, Length: 6776, dtype: bool

In [116]:
read_data[read_data.iloc[:, 0]=="non_person"].count()

0     1625
1     1625
2     1625
3     1625
4     1625
      ...
81    1625
82    1625
83    1625
84    1625
85    1625
Length: 86, dtype: int64

In [117]:
(read_data.iloc[:, 0]=="non_person").sum()

1625

In [125]:
(read_data.iloc[:, 0]=="person").sum()

5151

In [126]:
df

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,find me,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [130]:
df

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,find me,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [131]:
df3

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [135]:
final_df

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,59,54,55,56,45,63,52,67,45,...,163,96,121,99,121,96,116,82,96,84
0,person,43,8,26,30,19,15,35,36,20,...,48,55,62,32,55,44,35,41,57,39
0,non_person,92,77,91,96,74,91,81,106,62,...,82,199,153,171,125,179,140,127,119,142
0,person,212,130,51,19,69,87,147,163,173,...,269,230,184,180,155,137,105,108,77,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,person,69,74,76,66,70,69,78,58,93,...,132,170,196,154,134,162,140,123,113,136
0,person,44,24,46,38,21,52,38,65,30,...,144,64,94,74,96,52,88,71,72,56
0,person,11,20,3,4,7,13,16,9,13,...,19,44,36,27,7,23,28,16,9,17
0,person,83,58,92,78,61,89,74,83,63,...,105,187,148,164,117,191,139,130,114,163
0,non_person,32,49,39,53,53,36,61,47,69,...,91,97,126,76,94,83,101,74,79,73

In [137]:
read_data

,0,1,2,3,4,5,6,7,8,9,...,76,77,78,79,80,81,82,83,84,85
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
1,person,59,54,55,56,45,63,52,67,45,...,163,96,121,99,121,96,116,82,96,84
2,person,43,8,26,30,19,15,35,36,20,...,48,55,62,32,55,44,35,41,57,39
3,non_person,92,77,91,96,74,91,81,106,62,...,82,199,153,171,125,179,140,127,119,142
4,person,212,130,51,19,69,87,147,163,173,...,269,230,184,180,155,137,105,108,77,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6771,person,69,74,76,66,70,69,78,58,93,...,132,170,196,154,134,162,140,123,113,136
6772,person,44,24,46,38,21,52,38,65,30,...,144,64,94,74,96,52,88,71,72,56
6773,person,11,20,3,4,7,13,16,9,13,...,19,44,36,27,7,23,28,16,9,17
6774,person,83,58,92,78,61,89,74,83,63,...,105,187,148,164,117,191,139,130,114,163
6775,non_person,32,49,39,53,53,36,61,47,69,...,91,97,126,76,94,83,101,74,79,73

In [138]:
pd.concat([final_df, read_data])

,label,0,1,2,3,4,5,6,7,8,...,76,77,78,79,80,81,82,83,84,85
0,person,18,59,34,44,56,28,69,29,77,...,97,82,101,82,92,57,78,66,79,NaN
0,person,59,54,55,56,45,63,52,67,45,...,96,121,99,121,96,116,82,96,84,NaN
0,person,43,8,26,30,19,15,35,36,20,...,55,62,32,55,44,35,41,57,39,NaN
0,non_person,92,77,91,96,74,91,81,106,62,...,199,153,171,125,179,140,127,119,142,NaN
0,person,212,130,51,19,69,87,147,163,173,...,230,184,180,155,137,105,108,77,72,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6771,NaN,person,69,74,76,66,70,69,78,58,...,132,170,196,154,134,162,140,123,113,136.0
6772,NaN,person,44,24,46,38,21,52,38,65,...,144,64,94,74,96,52,88,71,72,56.0
6773,NaN,person,11,20,3,4,7,13,16,9,...,19,44,36,27,7,23,28,16,9,17.0
6774,NaN,person,83,58,92,78,61,89,74,83,...,105,187,148,164,117,191,139,130,114,163.0
6775,NaN,non_person,32,49,39,53,53,36,61,47,...,91,97,126,76,94,83,101,74,79,73.0

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,find me,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79

In [145]:
ls ../../Desktop/experiments_two\ 1703

Shared/  bisalgt/

In [146]:
import pandas as pd
import os, glob
import time

begining_start_time = time.time()

folder_locations = ["../../Desktop/experiments_one. 1703/", "../../Desktop/experiments_two 1703/", "../../Desktop/experiments_three 1703/"]


final_dataframe = pd.DataFrame()

for folder in folder_locations:
    start_time = time.time()
    path = folder + "binaries/"
    
    intermediate_df = pd.DataFrame()
    
    for filename in glob.glob(os.path.join(path, '*.npy')):
        with open(os.path.join(os.getcwd(), filename), 'r') as f: # open in readonly mode
            data = np.load(f.name)
            data_bytes = data.tobytes()
            
            # header_data = []
            # for i in struct.iter_unpack('@f', data_bytes[:64]):
            #     header_data.append(i[0])

            ultrasonic_data = []
            for i in struct.iter_unpack('@h',data_bytes[64:]):
                ultrasonic_data.append(i[0])

            tmp_df = pd.DataFrame([ultrasonic_data])

            label_output = f.name.split("/")[-1].split("_")[2]

            if label_output.lower() == "p":
                label_output = "person"
            else:
                label_output = "non_person"

            tmp_df.insert(0, "label", [label_output,])

            intermediate_df = pd.concat([intermediate_df, tmp_df])
    
    

    final_dataframe = pd.concat([final_dataframe, intermediate_df])
    print(time.time() - start_time)
    
final_dataframe.to_csv("final_dataframe.csv", index=False)  

print(time.time() - begining_start_time)

7.602364778518677
3.395035982131958
7.014578819274902
18.141904830932617

In [147]:
final_dataframe.count()

label    16355
0        16355
1        16355
2        16355
3        16355
         ...
80       16355
81       16355
82       16355
83       16355
84       16355
Length: 86, dtype: int64

In [148]:
(final_dataframe.iloc[:, 0] == "person").sum()

5564

In [149]:
(final_dataframe.iloc[:, 0] == "non_person").sum()

10791

In [150]:
final_dataframe.head()

,label,0,1,2,3,4,5,6,7,8,...,75,76,77,78,79,80,81,82,83,84
0,person,18,59,34,44,56,28,69,29,77,...,91,97,82,101,82,92,57,78,66,79
0,person,59,54,55,56,45,63,52,67,45,...,163,96,121,99,121,96,116,82,96,84
0,person,43,8,26,30,19,15,35,36,20,...,48,55,62,32,55,44,35,41,57,39
0,non_person,92,77,91,96,74,91,81,106,62,...,82,199,153,171,125,179,140,127,119,142
0,person,212,130,51,19,69,87,147,163,173,...,269,230,184,180,155,137,105,108,77,72