In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
        {
            "Name": [
                "Braund, Mr. Owen Harris",
                "Allen, Mr. William Henry",
                "Bonnell, Miss. Elizabeth",
            ],
            "Age": [22, 35, 58],
            "Sex": ["male", "male", "female"],
        }
    )

In [3]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [4]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

In [5]:
age = pd.Series([12,13,14], name='Age')

In [6]:
age

0    12
1    13
2    14
Name: Age, dtype: int64

In [7]:
age.name

'Age'

In [8]:
age.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
df['Age'].max()

58

In [10]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

In [11]:
ls

Wall_2911_test3.txt
pandas_tutor.ipynb
prediction_result_2911_test3_for_sync.json

In [2]:
df_camera = pd.read_json('prediction_result_2911_test3_for_sync.json')

In [3]:
df_camera.head()

,total_count,timestamp,prediction,detected_classes,stopped_timestamp
0,333,43821,person,"[{'label_int': 0, 'label': 'person', 'confiden...",43821.0
1,332,43820,person,"[{'label_int': 0, 'label': 'person', 'confiden...",NaN
2,331,43820,person,"[{'label_int': 0, 'label': 'person', 'confiden...",NaN
3,330,43819,person,"[{'label_int': 0, 'label': 'person', 'confiden...",NaN
4,329,43819,person,"[{'label_int': 0, 'label': 'person', 'confiden...",NaN

In [4]:
df_cv = df_camera.iloc[:, :3]

In [5]:
df_cv

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[333 rows x 3 columns]

In [6]:
df_rp = pd.read_csv('Wall_2911_test3.txt', header=None, sep='\n')

In [7]:
df_rp

                                                     0
0    19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
1    19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
2    19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
3    19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
4    19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
..                                                 ...
163  19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
164  19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
165  19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
166  19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...
167  19\t16384\t85\t0\t0\t3\t119,2093\t0\t1953125\t...

[168 rows x 1 columns]

In [8]:
df_r = df_rp[0].str.split(pat='\t', expand=True)

In [9]:

df_r

,0,1,2,3,4,5,6,7,8,9,...,16479,16480,16481,16482,16483,16484,16485,16486,16487,16488
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,31,56,40,67,35,67,46,64,41,
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,60,30,65,52,53,60,49,64,31,
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,28,59,36,66,50,60,57,55,56,
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,58,34,71,30,74,38,68,37,63,
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,45,56,55,70,43,72,48,71,33,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,37,54,48,65,40,69,45,65,40,
164,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,50,48,59,42,67,34,67,31,70,
165,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,27,60,35,69,43,66,54,62,53,
166,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,47,52,55,47,68,40,67,36,72,
167,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,30,61,39,65,45,55,58,53,63,

In [10]:
df_rp = df_rp[0].str.split( expand=True)

In [11]:
df_rp.iloc[32, :].shape

(16488,)

In [12]:
df_rp

,0,1,2,3,4,5,6,7,8,9,...,16478,16479,16480,16481,16482,16483,16484,16485,16486,16487
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,55,31,56,40,67,35,67,46,64,41
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,35,60,30,65,52,53,60,49,64,31
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,60,28,59,36,66,50,60,57,55,56
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,32,58,34,71,30,74,38,68,37,63
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,44,45,56,55,70,43,72,48,71,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,37,54,48,65,40,69,45,65,40
164,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,45,50,48,59,42,67,34,67,31,70
165,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,63,27,60,35,69,43,66,54,62,53
166,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,51,47,52,55,47,68,40,67,36,72
167,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,62,30,61,39,65,45,55,58,53,63

In [14]:
df_cv.shape

(333, 3)

In [16]:
df_r.shape

(168, 16489)

In [17]:
df_cv

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[333 rows x 3 columns]

In [18]:
df_r.iloc[11:28, 15:20]

      15 16 17     18    19
11  0,22  0  0  43498  -116
12  0,22  0  0  43499  -170
13  0,22  0  0  43499  -137
14  0,22  0  0  43504  -179
15  0,22  0  0  43504  -181
16  0,22  0  0  43510  -150
17  0,22  0  0  43510  -188
18  0,22  0  0  43510  -171
19  0,22  0  0  43512  -140
20  0,22  0  0  43515  -129
21  0,22  0  0  43515  -178
22  0,22  0  0  43516  -152
23  0,22  0  0  43516  -182
24  0,22  0  0  43528  -109
25  0,22  0  0  43528  -186
26  0,22  0  0  43528  -124
27  0,22  0  0  43528  -149

In [73]:
df_c.dtypes

total_count     int64
timestamp       int64
prediction     object
dtype: object

In [74]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   total_count  333 non-null    int64
 1   timestamp    333 non-null    int64
 2   prediction   333 non-null    object
dtypes: int64(2), object(1)
memory usage: 7.9+ KB

The head/tail/info methods and the dtypes attribute are convenient for a first check.

In [75]:
df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Columns: 16489 entries, 0 to 16488
dtypes: object(16489)
memory usage: 21.1+ MB

In [76]:
df_c.columns

Index(['total_count', 'timestamp', 'prediction'], dtype='object')

In [78]:
df_c['timestamp'].tail()

328    43422
329    43421
330    43421
331    43420
332    43420
Name: timestamp, dtype: int64

In [80]:
df_c[['timestamp', 'prediction']].tail()

     timestamp prediction
328      43422     person
329      43421     person
330      43421     person
331      43420     person
332      43420     person

In [82]:
df_c['timestamp'] > 43500

0       True
1       True
2       True
3       True
4       True
       ...
328    False
329    False
330    False
331    False
332    False
Name: timestamp, Length: 333, dtype: bool

In [20]:
df_cv[df_cv['timestamp'] > 43500].shape

(231, 3)

In [22]:
df_cv[df_cv['prediction'].isin(['others',])]

     total_count  timestamp prediction
274           59      43450     others
275           58      43449     others
276           57      43448     others
277           56      43448     others
278           55      43447     others

In [21]:
df_cv[df_cv['prediction'].isin(['person',])]

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[323 rows x 3 columns]

In [23]:
df_cv[df_cv['prediction'].isin(['chair',])]

     total_count  timestamp prediction
250           83      43462      chair
251           82      43461      chair
252           81      43461      chair
253           80      43460      chair
254           79      43460      chair

In [24]:
df_cv[(df_cv['prediction']== 'person')]

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[323 rows x 3 columns]

| == or-operator
& == and-operator

In [25]:
df_cv[(df_cv['prediction']== 'person') | (df_cv['prediction']== 'chair')]

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[328 rows x 3 columns]

In [27]:
df_cv.notna().shape

(333, 3)

In [28]:
df_r.shape

(168, 16489)

In [38]:
df_rp.notna().iloc[30:40,16485:]

    16485  16486  16487
30   True   True   True
31   True   True   True
32  False  False  False
33   True   True   True
34   True   True   True
35   True   True   True
36   True   True   True
37   True   True   True
38   True   True   True
39   True   True   True

In [39]:
df_r.notna().iloc[30:40,16485:]

    16485  16486  16487  16488
30   True   True   True   True
31   True   True   True   True
32  False  False  False  False
33   True   True   True   True
34   True   True   True   True
35   True   True   True   True
36   True   True   True   True
37   True   True   True   True
38   True   True   True   True
39   True   True   True   True

In [42]:
d1 = df_r.iloc[30:40,16485:]

In [36]:
df_rp.shape

(168, 16488)

In [37]:
df_r.shape

(168, 16489)

In [43]:
d1

   16485 16486 16487 16488
30    64    47    69
31    68    42    70
32  None  None  None  None
33    46    66    42
34    52    71    49
35    52    57    56
36    74    40    71
37    52    63    46
38    63    45    67
39    53    54    58

In [47]:
import numpy as np

In [49]:
d1[d1.isin(['', None, np.nan])]

    16485  16486  16487  16488
30  False  False  False   True
31  False  False  False   True
32   True   True   True   True
33  False  False  False   True
34  False  False  False   True
35  False  False  False   True
36  False  False  False   True
37  False  False  False   True
38  False  False  False   True
39  False  False  False   True

In [52]:
d1[d1.isin(['', None, np.nan])]

   16485 16486 16487 16488
30   NaN   NaN   NaN
31   NaN   NaN   NaN
32  None  None  None  None
33   NaN   NaN   NaN
34   NaN   NaN   NaN
35   NaN   NaN   NaN
36   NaN   NaN   NaN
37   NaN   NaN   NaN
38   NaN   NaN   NaN
39   NaN   NaN   NaN

In [53]:
d1==''

    16485  16486  16487  16488
30  False  False  False   True
31  False  False  False   True
32  False  False  False  False
33  False  False  False   True
34  False  False  False   True
35  False  False  False   True
36  False  False  False   True
37  False  False  False   True
38  False  False  False   True
39  False  False  False   True

In [55]:
d1[d1==''] = None

In [56]:
d1

   16485 16486 16487 16488
30    64    47    69  None
31    68    42    70  None
32  None  None  None  None
33    46    66    42  None
34    52    71    49  None
35    52    57    56  None
36    74    40    71  None
37    52    63    46  None
38    63    45    67  None
39    53    54    58  None

In [57]:
d1.isna()

    16485  16486  16487  16488
30  False  False  False   True
31  False  False  False   True
32   True   True   True   True
33  False  False  False   True
34  False  False  False   True
35  False  False  False   True
36  False  False  False   True
37  False  False  False   True
38  False  False  False   True
39  False  False  False   True

In [62]:
d1.loc[39, :] = np.nan

In [64]:
d1.isna()

    16485  16486  16487  16488
30  False  False  False   True
31  False  False  False   True
32   True   True   True   True
33  False  False  False   True
34  False  False  False   True
35  False  False  False   True
36  False  False  False   True
37  False  False  False   True
38  False  False  False   True
39   True   True   True   True

In [65]:
d1.notna()

    16485  16486  16487  16488
30   True   True   True  False
31   True   True   True  False
32  False  False  False  False
33   True   True   True  False
34   True   True   True  False
35   True   True   True  False
36   True   True   True  False
37   True   True   True  False
38   True   True   True  False
39  False  False  False  False

In [66]:
d1[d1.notna()]

   16485 16486 16487 16488
30    64    47    69   NaN
31    68    42    70   NaN
32   NaN   NaN   NaN   NaN
33    46    66    42   NaN
34    52    71    49   NaN
35    52    57    56   NaN
36    74    40    71   NaN
37    52    63    46   NaN
38    63    45    67   NaN
39   NaN   NaN   NaN   NaN

In [67]:
d1

   16485 16486 16487 16488
30    64    47    69  None
31    68    42    70  None
32  None  None  None  None
33    46    66    42  None
34    52    71    49  None
35    52    57    56  None
36    74    40    71  None
37    52    63    46  None
38    63    45    67  None
39   NaN   NaN   NaN   NaN

In [68]:
d1.dropna()

Empty DataFrame
Columns: [16485, 16486, 16487, 16488]
Index: []

In [74]:
d1.dropna(axis=1, how='all')

   16485 16486 16487
30    64    47    69
31    68    42    70
32  None  None  None
33    46    66    42
34    52    71    49
35    52    57    56
36    74    40    71
37    52    63    46
38    63    45    67
39   NaN   NaN   NaN

In [76]:
d1.dropna(axis=0, how='all').dropna(axis=1, how='all')

   16485 16486 16487
30    64    47    69
31    68    42    70
33    46    66    42
34    52    71    49
35    52    57    56
36    74    40    71
37    52    63    46
38    63    45    67

For both the part before and after the comma, you can use a single label, a list of labels, a slice of labels, a conditional expression or a colon. Using a colon specifies you want to select all rows or columns. (iloc, loc) for row and column

In [79]:
df_r.columns

RangeIndex(start=0, stop=16489, step=1)

In [80]:
df_r.index

RangeIndex(start=0, stop=168, step=1)

## Test Merging

In [96]:
import pandas as pd

df1 = pd.DataFrame({'A':[1,2,3, 3], 'B':[11,12,13, 33]})

In [97]:
df1

   A   B
0  1  11
1  2  12
2  3  13
3  3  33

In [98]:
df2 = pd.DataFrame({'X':[1,3,5], 'Y':[1111,1112,1113], 'Z':[2222,2223,2224]})

In [99]:
df2

   X     Y     Z
0  1  1111  2222
1  3  1112  2223
2  5  1113  2224

In [100]:
pd.merge(df2, df1, how='inner', left_on='X', right_on='A')

   X     Y     Z  A   B
0  1  1111  2222  1  11
1  3  1112  2223  3  13
2  3  1112  2223  3  33

In [101]:
pd.merge(df2, df1, how='inner', left_on='X', right_on='A', indicator=True)

   X     Y     Z  A   B _merge
0  1  1111  2222  1  11   both
1  3  1112  2223  3  13   both
2  3  1112  2223  3  33   both

In [102]:
pd.merge(df2, df1, how='outer', left_on='X', right_on='A', indicator=True)

     X       Y       Z    A     B      _merge
0  1.0  1111.0  2222.0  1.0  11.0        both
1  3.0  1112.0  2223.0  3.0  13.0        both
2  3.0  1112.0  2223.0  3.0  33.0        both
3  5.0  1113.0  2224.0  NaN   NaN   left_only
4  NaN     NaN     NaN  2.0  12.0  right_only

In [103]:
df_r

,0,1,2,3,4,5,6,7,8,9,...,16479,16480,16481,16482,16483,16484,16485,16486,16487,16488
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,31,56,40,67,35,67,46,64,41,
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,60,30,65,52,53,60,49,64,31,
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,28,59,36,66,50,60,57,55,56,
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,58,34,71,30,74,38,68,37,63,
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,45,56,55,70,43,72,48,71,33,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,37,54,48,65,40,69,45,65,40,
164,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,50,48,59,42,67,34,67,31,70,
165,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,27,60,35,69,43,66,54,62,53,
166,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,47,52,55,47,68,40,67,36,72,
167,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,30,61,39,65,45,55,58,53,63,

In [106]:
df_r.iloc[:, 18]

0      43480
1      43482
2      43482
3      43482
4      43482
       ...
163    43822
164    43822
165    43823
166    43823
167    43823
Name: 18, Length: 168, dtype: object

In [104]:
df_cv

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[333 rows x 3 columns]

In [108]:
df_cv.dtypes

total_count     int64
timestamp       int64
prediction     object
dtype: object

In [109]:
df_r.dtypes

0        object
1        object
2        object
3        object
4        object
          ...
16484    object
16485    object
16486    object
16487    object
16488    object
Length: 16489, dtype: object

In [111]:
df_r[18]

0      43480
1      43482
2      43482
3      43482
4      43482
       ...
163    43822
164    43822
165    43823
166    43823
167    43823
Name: 18, Length: 168, dtype: object

In [112]:
df_r[18].astype('int64').dtypes

dtype('int64')

In [113]:
df_r[18].astype('int64', copy=False)

0      43480
1      43482
2      43482
3      43482
4      43482
       ...
163    43822
164    43822
165    43823
166    43823
167    43823
Name: 18, Length: 168, dtype: int64

In [118]:
df_r[18] = df_r[18].astype('int64')

In [136]:
df_merged = pd.merge(df_r, df_cv, how='outer', left_on=18, right_on='timestamp', indicator=True)

In [145]:
df_merged.to_csv('merged_test.csv', header=None, sep='\t')

In [122]:
df_merged.to_excel('merged_excel.xlsx', header=None)

ValueError: This sheet is too large! Your sheet size is: 498, 16493 Max sheet size is: 1048576, 16384

In [124]:
df_merged

,0,1,2,3,4,5,6,7,8,9,...,16483,16484,16485,16486,16487,16488,total_count,timestamp,prediction,_merge
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,35,67,46,64,41,,NaN,NaN,NaN,left_only
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,60,49,64,31,,NaN,NaN,NaN,left_only
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,50,60,57,55,56,,NaN,NaN,NaN,left_only
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,74,38,68,37,63,,NaN,NaN,NaN,left_only
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,43,72,48,71,33,,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,43422.0,person,right_only
494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,43421.0,person,right_only
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,43421.0,person,right_only
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,43420.0,person,right_only
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,43420.0,person,right_only

In [126]:
df_merged[df_merged['prediction'].isin(['person',])]

,0,1,2,3,4,5,6,7,8,9,...,16483,16484,16485,16486,16487,16488,total_count,timestamp,prediction,_merge
71,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,77,54,81,39,74,,183.0,43636.0,person,both
117,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,254.0,43728.0,person,both
118,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,253.0,43728.0,person,both
119,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,260.0,43731.0,person,both
120,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,259.0,43731.0,person,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,43422.0,person,right_only
494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,43421.0,person,right_only
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,43421.0,person,right_only
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,43420.0,person,right_only
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,43420.0,person,right_only

In [127]:
df_merged.shape

(498, 16493)

In [132]:
df_merged['timestamp'].notna()

0      False
1      False
2      False
3      False
4      False
       ...
493     True
494     True
495     True
496     True
497     True
Name: timestamp, Length: 498, dtype: bool

In [133]:
df_merged[df_merged['timestamp'].notna()]

,0,1,2,3,4,5,6,7,8,9,...,16483,16484,16485,16486,16487,16488,total_count,timestamp,prediction,_merge
71,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,77,54,81,39,74,,183.0,43636.0,person,both
117,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,254.0,43728.0,person,both
118,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,253.0,43728.0,person,both
119,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,260.0,43731.0,person,both
120,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,259.0,43731.0,person,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,43422.0,person,right_only
494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,43421.0,person,right_only
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,43421.0,person,right_only
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,43420.0,person,right_only
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,43420.0,person,right_only

In [140]:
df_merged_inner = pd.merge(df_r, df_cv, how='inner', left_on=[18,], right_on='timestamp', indicator=True)

In [141]:
df_merged_inner

,0,1,2,3,4,5,6,7,8,9,...,16483,16484,16485,16486,16487,16488,total_count,timestamp,prediction,_merge
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,77,54,81,39,74,,183,43636,person,both
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,254,43728,person,both
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,253,43728,person,both
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,260,43731,person,both
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,259,43731,person,both
5,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,65,43,68,40,72,,260,43731,person,both
6,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,65,43,68,40,72,,259,43731,person,both
7,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,62,46,67,41,71,,264,43743,person,both
8,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,62,46,67,41,71,,263,43743,person,both
9,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,35,69,44,61,41,,264,43743,person,both
10,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,35,69,44,61,41,,263,43743,person,both
11,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,67,34,66,40,63,,290,43775,person,both
12,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,64,48,59,49,51,,290,43775,person,both
13,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,66,43,71,36,68,,290,43775,person,both

In [142]:
df_r.columns

RangeIndex(start=0, stop=16489, step=1)

In [144]:
df_r[18].

<bound method Series.rename of 0      43480
1      43482
2      43482
3      43482
4      43482
       ...
163    43822
164    43822
165    43823
166    43823
167    43823
Name: 18, Length: 168, dtype: int64>

In [146]:
df_r.rename(columns={18: "timestamp"}, inplace=True)

In [147]:
df_merged_inner_2 = pd.merge(df_r, df_cv, how='inner', on='timestamp', indicator=True)

In [148]:
df_merged_inner_2.shape

(14, 16492)

In [149]:
df_merged_inner.head()

,0,1,2,3,4,5,6,7,8,9,...,16483,16484,16485,16486,16487,16488,total_count,timestamp,prediction,_merge
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,77,54,81,39,74,,183,43636,person,both
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,254,43728,person,both
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,53,53,56,45,62,,253,43728,person,both
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,260,43731,person,both
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,70,37,69,37,67,,259,43731,person,both

In [150]:
df_merged_inner_2.head()

,0,1,2,3,4,5,6,7,8,9,...,16482,16483,16484,16485,16486,16487,16488,total_count,prediction,_merge
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,55,77,54,81,39,74,,183,person,both
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,57,53,53,56,45,62,,254,person,both
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,57,53,53,56,45,62,,253,person,both
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,33,70,37,69,37,67,,260,person,both
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,33,70,37,69,37,67,,259,person,both

In [152]:
df_merged_inner_2['prediction']=='person'

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
Name: prediction, dtype: bool

In [153]:
df1

   A   B
0  1  11
1  2  12
2  3  13
3  3  33

In [154]:
df2

   X     Y     Z
0  1  1111  2222
1  3  1112  2223
2  5  1113  2224

In [155]:
pd.merge(df2,df1, left_on='X', right_on='A', how='left', indicator=True)

   X     Y     Z    A     B     _merge
0  1  1111  2222  1.0  11.0       both
1  3  1112  2223  3.0  13.0       both
2  3  1112  2223  3.0  33.0       both
3  5  1113  2224  NaN   NaN  left_only

In [157]:
df_r.columns

Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
       ...
       16479, 16480, 16481, 16482, 16483, 16484, 16485, 16486, 16487, 16488],
      dtype='object', length=16489)

In [158]:
df_r['timestamp']

0      43480
1      43482
2      43482
3      43482
4      43482
       ...
163    43822
164    43822
165    43823
166    43823
167    43823
Name: timestamp, Length: 168, dtype: int64

In [159]:
df_cv

     total_count  timestamp prediction
0            333      43821     person
1            332      43820     person
2            331      43820     person
3            330      43819     person
4            329      43819     person
..           ...        ...        ...
328            5      43422     person
329            4      43421     person
330            3      43421     person
331            2      43420     person
332            1      43420     person

[333 rows x 3 columns]

In [161]:
df_merged = pd.merge(df_r, df_cv, how='left', left_on='timestamp', right_on='timestamp')

In [162]:
df_merged

,0,1,2,3,4,5,6,7,8,9,...,16481,16482,16483,16484,16485,16486,16487,16488,total_count,prediction
0,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,40,67,35,67,46,64,41,,NaN,NaN
1,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,65,52,53,60,49,64,31,,NaN,NaN
2,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,36,66,50,60,57,55,56,,NaN,NaN
3,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,71,30,74,38,68,37,63,,NaN,NaN
4,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,55,70,43,72,48,71,33,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,48,65,40,69,45,65,40,,NaN,NaN
169,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,59,42,67,34,67,31,70,,NaN,NaN
170,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,35,69,43,66,54,62,53,,NaN,NaN
171,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,55,47,68,40,67,36,72,,NaN,NaN
172,19,16384,85,0,0,3,"119,2093",0,1953125,12,...,39,65,45,55,58,53,63,,NaN,NaN

In [165]:
set(df_merged["prediction"])

{nan, 'person'}

In [223]:
df_cv = pd.read_json('data/prediction_result_2511_test6_with_timestamp.json')

In [224]:
df_cv

     total_count  timestamp prediction
0            177      59380      chair
1            176      59380      chair
2            175      59378      chair
3            174      59376      chair
4            173      59375      chair
..           ...        ...        ...
172            5      59172     person
173            4      59171     person
174            3      59171     person
175            2      59170     person
176            1      59169     person

[177 rows x 3 columns]

In [225]:
df_cv['timestamp'] = df_cv['timestamp'].apply(lambda x: x - 3600)

In [226]:
df_cv

     total_count  timestamp prediction
0            177      55780      chair
1            176      55780      chair
2            175      55778      chair
3            174      55776      chair
4            173      55775      chair
..           ...        ...        ...
172            5      55572     person
173            4      55571     person
174            3      55571     person
175            2      55570     person
176            1      55569     person

[177 rows x 3 columns]

In [230]:
df_rps = pd.read_csv('data/Wall_test6.txt', header=None, sep='\n')
df_rps = df_rps[0].str.split(pat='\t', expand=True)
df_rps[18] = df_rps[18].astype('int64')

df_rps.shape

(800, 16404)

In [231]:
df_rps.head()

,0,1,2,3,4,5,6,7,8,9,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,19,16384,0,0,1,1,"119,2093",0,1953125,12,...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
1,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
2,19,16384,0,0,1,1,"119,2093",0,1953125,12,...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
3,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
4,19,16384,0,0,0,1,"119,2093",0,1953125,12,...,-149,-144,-147,-148,-154,-149,-144,-150,-148,

In [232]:
df_rps[18]

0      55593
1      55594
2      55594
3      55594
4      55594
       ...
795    55763
796    55763
797    55764
798    55764
799    55764
Name: 18, Length: 800, dtype: int64

In [173]:
pd.merge(df_cv, df_rps, right_on=18, left_on='timestamp')

ValueError: You are trying to merge on int64 and object columns. If you wish to proceed you should use pd.concat

In [233]:
pd.merge(df_cv, df_rps, right_on=18, left_on='timestamp')

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,166,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,
1,166,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,
2,166,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,
3,165,55762,chair,19,16384,0,0,0,1,"119,2093",...,-204,-203,-207,-208,-209,-210,-213,-211,-214,
4,165,55762,chair,19,16384,0,0,0,1,"119,2093",...,-171,-175,-175,-173,-170,-173,-172,-171,-176,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638,32,55596,person,19,16384,0,0,1,1,"119,2093",...,-114,-114,-114,-115,-123,-119,-115,-119,-116,
639,31,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
640,31,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
641,31,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
642,31,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,

In [217]:
pd.merge(df_cv, df_rps, right_on=18, left_on='timestamp')

Empty DataFrame
Columns: [total_count, timestamp, prediction, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, ...]
Index: []

[0 rows x 16407 columns]

In [277]:
df_mg = pd.merge(df_cv, df_rps, how='right', right_on=18, left_on='timestamp')
df_mg

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,

In [235]:
df_copy = df_mg.copy()

In [236]:
df_copy

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,

In [242]:
df_copy.loc[df_copy['prediction'].isna(), 'prediction'] = 'others'

In [243]:
df_copy

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,others,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,others,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,others,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,

In [222]:
df_mg[df_mg['prediction'].notna()]

Empty DataFrame
Columns: [total_count, timestamp, prediction, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, ...]
Index: []

[0 rows x 16407 columns]

In [193]:
df_mg['prediction'].shape

(800,)

In [192]:
df_mg['prediction'][(df_mg['prediction'].isna()) ]

0      NaN
5      NaN
6      NaN
7      NaN
8      NaN
      ...
792    NaN
793    NaN
794    NaN
795    NaN
796    NaN
Name: prediction, Length: 157, dtype: object

In [195]:
df_mg['prediction'].isna()

0       True
1      False
2      False
3      False
4      False
       ...
795     True
796     True
797    False
798    False
799    False
Name: prediction, Length: 800, dtype: bool

In [196]:
df_mg[(df_mg['prediction'].isna()) ]

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
5,NaN,55595,NaN,19,16384,0,0,1,1,"119,2093",...,-146,-151,-149,-149,-145,-146,-150,-149,-151,
6,NaN,55595,NaN,19,16384,0,0,0,1,"119,2093",...,-158,-156,-151,-152,-155,-154,-153,-157,-156,
7,NaN,55595,NaN,19,16384,0,0,0,1,"119,2093",...,-156,-159,-160,-163,-164,-161,-158,-162,-159,
8,NaN,55595,NaN,19,16384,0,0,0,1,"119,2093",...,-135,-131,-129,-126,-128,-128,-126,-130,-131,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,NaN,55763,NaN,19,16384,0,0,1,1,"119,2093",...,-171,-167,-168,-166,-164,-168,-171,-167,-163,
793,NaN,55763,NaN,19,16384,0,0,1,1,"119,2093",...,-160,-163,-167,-166,-162,-171,-172,-168,-170,
794,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-139,-144,-144,-143,-147,-153,-154,-157,-162,
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,

In [198]:
df_mg = df_mg[(df_mg['prediction'].isna()) ]
df_mg

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
5,NaN,55595,NaN,19,16384,0,0,1,1,"119,2093",...,-146,-151,-149,-149,-145,-146,-150,-149,-151,
6,NaN,55595,NaN,19,16384,0,0,0,1,"119,2093",...,-158,-156,-151,-152,-155,-154,-153,-157,-156,
7,NaN,55595,NaN,19,16384,0,0,0,1,"119,2093",...,-156,-159,-160,-163,-164,-161,-158,-162,-159,
8,NaN,55595,NaN,19,16384,0,0,0,1,"119,2093",...,-135,-131,-129,-126,-128,-128,-126,-130,-131,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,NaN,55763,NaN,19,16384,0,0,1,1,"119,2093",...,-171,-167,-168,-166,-164,-168,-171,-167,-163,
793,NaN,55763,NaN,19,16384,0,0,1,1,"119,2093",...,-160,-163,-167,-166,-162,-171,-172,-168,-170,
794,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-139,-144,-144,-143,-147,-153,-154,-157,-162,
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,

In [199]:
df_mg[(df_mg['prediction'].isna()) ] = 'others'

In [200]:
df_mg

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
5,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
6,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
7,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
8,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
793,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
794,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
795,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others
796,others,others,others,others,others,others,others,others,others,others,...,others,others,others,others,others,others,others,others,others,others

In [201]:
df1

   A   B
0  1  11
1  2  12
2  3  13
3  3  33

In [202]:
df2

   X     Y     Z
0  1  1111  2222
1  3  1112  2223
2  5  1113  2224

In [204]:
df2['X'] == 3

0    False
1     True
2    False
Name: X, dtype: bool

In [205]:
df2[df2['X'] == 3]

   X     Y     Z
1  3  1112  2223

In [208]:
df2.loc[df2['X'] == 3, 'X'] = 30

In [209]:
df2

    X     Y     Z
0   1  1111  2222
1  30  1112  2223
2   5  1113  2224

In [244]:
df_mg

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,

In [245]:
df_mg.shape

(800, 16407)

In [246]:
df_mg.dropna(axis=1, how='all')

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,

In [252]:
import numpy as np
df_mg.isin(['', None, np.nan])

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
796,True,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
797,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
798,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
799,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [255]:
df_mg[df_mg.isin(['', None, np.nan])]

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
799,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [275]:
import numpy as np
def func(x):
    if x in ['', None, np.nan]:
        return np.nan
    return x


df_copy= df_copy.applymap(func)
df_copy

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,others,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,NaN
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,NaN
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,NaN
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,NaN
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,others,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,NaN
796,NaN,55763,others,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,NaN
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,NaN
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,NaN
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,NaN

In [276]:
df_copy.dropna(axis=1, how='all', inplace=True)
df_copy.dropna(axis=0, how='all', inplace=True)
df_copy

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,NaN,55593,others,19,16384,0,0,1,1,"119,2093",...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,others,19,16384,0,0,0,1,"119,2093",...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,NaN,55763,others,19,16384,0,0,0,1,"119,2093",...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [271]:
df_mg.dropna(axis=1, how='all', inplace=True)
df_mg.dropna(axis=0, how='all', inplace=True)

In [272]:
df_mg.shape

(800, 16406)

In [279]:
def make_consistent_na(series):
    series[series.isin(['', None, np.nan])] = np.nan
    return series


df_mg.apply(make_consistent_na)

,total_count,timestamp,prediction,0,1,2,3,4,5,6,...,16394,16395,16396,16397,16398,16399,16400,16401,16402,16403
0,NaN,55593,NaN,19,16384,0,0,1,1,"119,2093",...,-150,-154,-150,-155,-159,-166,-167,-169,-162,NaN
1,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-179,-177,-178,-176,-173,-172,-168,-166,-167,NaN
2,31.0,55594,person,19,16384,0,0,1,1,"119,2093",...,-144,-145,-146,-144,-146,-141,-143,-149,-152,NaN
3,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-157,-159,-163,-162,-163,-159,-159,-157,-156,NaN
4,31.0,55594,person,19,16384,0,0,0,1,"119,2093",...,-149,-144,-147,-148,-154,-149,-144,-150,-148,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,NaN
796,NaN,55763,NaN,19,16384,0,0,0,1,"119,2093",...,-144,-147,-150,-148,-150,-158,-164,-162,-161,NaN
797,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-150,-152,-151,-148,-150,-149,-146,-147,-143,NaN
798,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-139,-135,-134,-132,-134,-133,-133,-129,-131,NaN
799,166.0,55764,chair,19,16384,0,0,0,1,"119,2093",...,-123,-122,-117,-122,-123,-125,-130,-134,-137,NaN

In [280]:
import time

t1 = time.time()

df_mg.apply(make_consistent_na)

t2 = time.time()

print("time taken for series operation : ", t2 - t1)


t3 = time.time()
df_mg.applymap(func)
t4 = time.time()

print("time taken for elementwise operation : ", t4 - t3)

time taken for series operation :  33.10426115989685
time taken for elementwise operation :  5.125396013259888

In [288]:
import pandas as pd
import numpy as np
import time

t1 = time.time()

def replace_missing(x):
    if x in ['', None, np.nan]:
        return np.nan
    return x


df_cv = pd.read_json('data/prediction_result_2511_test6_with_timestamp.json')
df_cv['timestamp'] = df_cv['timestamp'].apply(lambda x: x - 3600)
df_cv = df_cv[['timestamp', 'prediction']]

df_rps = pd.read_csv('data/Wall_test6.txt', header=None, sep='\n')
df_rps = df_rps[0].str.split(pat='\t', expand=True)
df_rps[18] = df_rps[18].astype('int64')
df_rps = df_rps.applymap(replace_missing)

df_mg = pd.merge(df_cv, df_rps, how='right', right_on=18, left_on='timestamp')
df_mg.loc[df_mg['prediction'].isna(), 'prediction'] = 'others'
df_mg.dropna(axis=1, how='all', inplace=True)
df_mg.dropna(axis=0, how='all', inplace=True)

t2 = time.time()

print("Total time taken : ", t2- t1)

Total time taken :  13.816611051559448

In [289]:
df_mg

,timestamp,prediction,0,1,2,3,4,5,6,7,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55593,others,19,16384,0,0,1,1,"119,2093",0,...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
1,55594,person,19,16384,0,0,0,1,"119,2093",0,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,55594,person,19,16384,0,0,1,1,"119,2093",0,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,55594,person,19,16384,0,0,0,1,"119,2093",0,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,55594,person,19,16384,0,0,0,1,"119,2093",0,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,55763,others,19,16384,0,0,0,1,"119,2093",0,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,55763,others,19,16384,0,0,0,1,"119,2093",0,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
797,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [290]:
df_mg[df_mg['prediction'] == 'person']

,timestamp,prediction,0,1,2,3,4,5,6,7,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
1,55594,person,19,16384,0,0,0,1,"119,2093",0,...,-178,-179,-177,-178,-176,-173,-172,-168,-166,-167
2,55594,person,19,16384,0,0,1,1,"119,2093",0,...,-145,-144,-145,-146,-144,-146,-141,-143,-149,-152
3,55594,person,19,16384,0,0,0,1,"119,2093",0,...,-155,-157,-159,-163,-162,-163,-159,-159,-157,-156
4,55594,person,19,16384,0,0,0,1,"119,2093",0,...,-155,-149,-144,-147,-148,-154,-149,-144,-150,-148
9,55596,person,19,16384,0,0,1,1,"119,2093",0,...,-164,-170,-178,-175,-180,-182,-182,-181,-178,-173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,55676,person,19,16384,0,0,1,1,"119,2093",0,...,-168,-169,-169,-169,-174,-174,-174,-174,-174,-171
358,55677,person,19,16384,0,0,1,1,"119,2093",0,...,-83,-85,-86,-88,-89,-91,-94,-94,-92,-89
359,55677,person,19,16384,0,0,1,1,"119,2093",0,...,-139,-144,-149,-159,-160,-169,-167,-166,-172,-172
360,55677,person,19,16384,0,0,1,1,"119,2093",0,...,-129,-134,-129,-130,-137,-143,-144,-144,-149,-151
361,55677,person,19,16384,0,0,0,1,"119,2093",0,...,-143,-148,-150,-151,-155,-159,-163,-166,-167,-172

In [291]:
df_mg[df_mg['prediction'] == 'chair']

,timestamp,prediction,0,1,2,3,4,5,6,7,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
367,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-187,-190,-191,-190,-193,-196,-194,-197,-194,-186
368,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-65,-54,-42,-36,-29,-30,-40,-43,-48,-53
369,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
370,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
371,55680,chair,19,16384,0,0,1,1,"119,2093",0,...,-140,-141,-146,-147,-149,-154,-160,-164,-172,-171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
787,55762,chair,19,16384,0,0,0,1,"119,2093",0,...,-159,-160,-161,-163,-165,-166,-167,-168,-171,-173
788,55762,chair,19,16384,0,0,0,1,"119,2093",0,...,-148,-151,-157,-165,-162,-164,-163,-163,-167,-168
797,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
798,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
799,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [292]:
df_mg[df_mg['prediction'] == 'others']

,timestamp,prediction,0,1,2,3,4,5,6,7,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55593,others,19,16384,0,0,1,1,"119,2093",0,...,-146,-150,-154,-150,-155,-159,-166,-167,-169,-162
5,55595,others,19,16384,0,0,1,1,"119,2093",0,...,-139,-146,-151,-149,-149,-145,-146,-150,-149,-151
6,55595,others,19,16384,0,0,0,1,"119,2093",0,...,-154,-158,-156,-151,-152,-155,-154,-153,-157,-156
7,55595,others,19,16384,0,0,0,1,"119,2093",0,...,-160,-156,-159,-160,-163,-164,-161,-158,-162,-159
8,55595,others,19,16384,0,0,0,1,"119,2093",0,...,-139,-135,-131,-129,-126,-128,-128,-126,-130,-131
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,55763,others,19,16384,0,0,1,1,"119,2093",0,...,-170,-171,-167,-168,-166,-164,-168,-171,-167,-163
793,55763,others,19,16384,0,0,1,1,"119,2093",0,...,-157,-160,-163,-167,-166,-162,-171,-172,-168,-170
794,55763,others,19,16384,0,0,0,1,"119,2093",0,...,-138,-139,-144,-144,-143,-147,-153,-154,-157,-162
795,55763,others,19,16384,0,0,0,1,"119,2093",0,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161
796,55763,others,19,16384,0,0,0,1,"119,2093",0,...,-139,-144,-147,-150,-148,-150,-158,-164,-162,-161

In [294]:
df_mg[df_mg['prediction'] == 'others'].to_csv('processed/others.json')

In [295]:
df_mg[df_mg['prediction'] == 'person'].to_csv('processed/person.json')

In [296]:
df_mg[df_mg['prediction'] == 'chair'].to_csv('processed/chair.json')

In [298]:
pd.read_csv('processed/chair.json', index_col=None)

,Unnamed: 0,timestamp,prediction,0,1,2,3,4,5,6,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,367,55679,chair,19,16384,0,0,1,1,"119,2093",...,-187,-190,-191,-190,-193,-196,-194,-197,-194,-186
1,368,55679,chair,19,16384,0,0,1,1,"119,2093",...,-65,-54,-42,-36,-29,-30,-40,-43,-48,-53
2,369,55679,chair,19,16384,0,0,1,1,"119,2093",...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
3,370,55679,chair,19,16384,0,0,1,1,"119,2093",...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
4,371,55680,chair,19,16384,0,0,1,1,"119,2093",...,-140,-141,-146,-147,-149,-154,-160,-164,-172,-171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,787,55762,chair,19,16384,0,0,0,1,"119,2093",...,-159,-160,-161,-163,-165,-166,-167,-168,-171,-173
400,788,55762,chair,19,16384,0,0,0,1,"119,2093",...,-148,-151,-157,-165,-162,-164,-163,-163,-167,-168
401,797,55764,chair,19,16384,0,0,0,1,"119,2093",...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
402,798,55764,chair,19,16384,0,0,0,1,"119,2093",...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
403,799,55764,chair,19,16384,0,0,0,1,"119,2093",...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137

In [302]:
df_mg[df_mg['prediction'] == 'chair'].to_csv('processed/chair.json', index=False)

In [300]:
pd.read_csv('processed/chair.json')

,timestamp,prediction,0,1,2,3,4,5,6,7,...,16393,16394,16395,16396,16397,16398,16399,16400,16401,16402
0,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-187,-190,-191,-190,-193,-196,-194,-197,-194,-186
1,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-65,-54,-42,-36,-29,-30,-40,-43,-48,-53
2,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
3,55679,chair,19,16384,0,0,1,1,"119,2093",0,...,-111,-117,-120,-125,-130,-133,-142,-151,-152,-155
4,55680,chair,19,16384,0,0,1,1,"119,2093",0,...,-140,-141,-146,-147,-149,-154,-160,-164,-172,-171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,55762,chair,19,16384,0,0,0,1,"119,2093",0,...,-159,-160,-161,-163,-165,-166,-167,-168,-171,-173
400,55762,chair,19,16384,0,0,0,1,"119,2093",0,...,-148,-151,-157,-165,-162,-164,-163,-163,-167,-168
401,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-148,-150,-152,-151,-148,-150,-149,-146,-147,-143
402,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-144,-139,-135,-134,-132,-134,-133,-133,-129,-131
403,55764,chair,19,16384,0,0,0,1,"119,2093",0,...,-121,-123,-122,-117,-122,-123,-125,-130,-134,-137